### PR TITLE
Add `-owarpinv` to `sct_register_multimodal`

### LINKED ISSUE #1530: enable to specify output warping field name

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

This PR add the ability to specify the filename of the output inverse warping field. This is relevant for the SCT Course, since we often would rename the files using `mv` (because the auto-generated filenames were long and awkward).

For this PR, I've tried to mimic the existing programming conventions in `sct_register_multimodal` (basically just matching `-owarp` without making any further improvements), just to keep the changes easier to understand/review. 

## Linked issues

Fixes #1530.

### CODE REVIEW

**Review by sandrinebedard — COMMENTED** [review]
I tested it out with `-owarpinv` and it works well! However, when I don't  specify the flag, the inverse warping field is not created, but it should be... this may explain the batch pocessing test failling

**Comment by joshuacwnewton** [comment]
> I tested it out with `-owarpinv` and it works well! However, when I don't specify the flag, the inverse warping field is not created, but it should be... this may explain the batch pocessing test failling

Oops. There was a typo on my part. Sorry about that. :sweat_smile:

**Review by sandrinebedard — APPROVED** [review]
Works well now! 🎉

One suggestion, we could also remove the lines renaming the warping fileds in `batch_processing.sh` and use `-owarp` and `-owarpinv` as we want to do in the tutorials 😊

**Comment by joshuacwnewton** [comment]
> One suggestion, we could also remove the lines renaming the warping fileds in `batch_processing.sh` and use `-owarp` and `-owarpinv` as we want to do in the tutorials :blush:

Ahhh, that's a very good point! Thank you for the reminder. It's easy to forget. :sweat_smile: 

As an aside, it might be worth investigating how much overlap there is between [`batch_processing.sh`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/batch_processing.sh) and [`batch_single_subject.sh`](https://github.com/spinalcordtoolbox/sct_tutorial_data/blob/master/single_subject/batch_single_subject.sh) from the tutorials. If there was a way to use a single script for both purposes, that could save us some maintenance effort, since we would be keeping our batch_processing.sh script in sync with the tutorials.

**Pull request merged**
