### PR TITLE
Refactor the `interpolate_metrics` function to simplify and shorten it

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

This PR proposes some additional changes for @sandrinebedard's normalization PR, #3977. I'm using the "PR format" because the changes are a bit complex, and so it's easier for me to demonstrate each change using individual commits, as opposed to explaining them in review comments on #3977.

This PR contains purely refactoring; there are no functional changes here, just code reorganization. (I used the modified test to confirm that there are no changes; at each commit, the test passes.)

The goal of this refactoring is to simplify and shorten the `interpolate_metrics` function, so that it is easier to read and understand, thus paving the way for further reviews of the functionality.

## Reviewing this PR

I'd recommend using the "Commits" view, since each commit contains an extended commit description to explain the reasoning behind each commit. 

Feel free to discuss/ask questions/push back against my suggestions/etc. :smile: 

## Note

Since this is a PR into _another_ PR, I have not tagged this with milestones/labels, since it's a smaller part of a larger PR.

### CODE REVIEW

**Review by sandrinebedard — COMMENTED** [review]
When I run this test, this is what I get an assertion error:

~~~
Traceback (most recent call last):
  File "/mnt/c/Users/sb199/spinalcordtoolbox/testing/cli/test_cli_sct_process_segmentation.py", line 111, in test_sct_process_segmentation_check_normalize_PAM50
    assert row['MEAN(area)'] == pytest.approx('71.9688049386959')
AssertionError: assert '71.96880493869594' == 71.9688049386959
  comparison failed
  Obtained: 71.96880493869594
  Expected: 71.9688049386959
~~~

<details>
  <summary>terminal</summary>

~~~
(venv_sct) sabeda@DESKTOP-JQ8A4UV:/mnt/c/Users/sb199/spinalcordtoolbox$ pytest testing/cli/test_cli_sct_process_segmentation.py
================================================= test session starts ==================================================
platform linux -- Python 3.7.13, pytest-7.1.2, pluggy-1.0.0 -- /mnt/c/Users/sb199/spinalcordtoolbox/python/envs/venv_sct/bin/python3
cachedir: .pytest_cache
rootdir: /mnt/c/Users/sb199/spinalcordtoolbox, configfile: setup.cfg
plugins: console-scripts-1.3.1, cov-3.0.0
collected 10 items

testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_pmj PASSED                 [ 10%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_pmj_perslice PASSED        [ 20%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_missing_pmj_args PASSED          [ 30%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize PASSED           [ 40%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize_missing_value PASSED [ 50%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize_missing_predictor PASSED [ 60%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize_PAM50 FAILED     [ 70%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize_PAM50_missing_perslice PASSED [ 80%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize_PAM50_missing_vertfile PASSED [ 90%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_no_checks PASSED                 [100%]
testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_no_checks ERROR                  [100%]

======================================================== ERRORS ========================================================
_____________________________ ERROR at teardown of test_sct_process_segmentation_no_checks _____________________________
Traceback (most recent call last):
  File "/mnt/c/Users/sb199/spinalcordtoolbox/testing/conftest.py", line 59, in <lambda>
    request.addfinalizer(lambda: check_testing_data_integrity(files_checksums))
  File "/mnt/c/Users/sb199/spinalcordtoolbox/testing/conftest.py", line 94, in check_testing_data_integrity
    assert not changed
AssertionError: assert not [('/mnt/c/Users/sb199/spinalcordtoolbox/data/sct_testing_data/csa.csv', '759f86be1a6d7da1ec0472e063d81354')]
------------------------------------------------- Captured stderr call -------------------------------------------------
Compute shape analysis: 100%|################| 55/55 [00:00<00:00, 354.54iter/s]
Aggregating metrics: 100%|####################| 9/9 [00:00<00:00, 9015.70iter/s]
======================================================= FAILURES =======================================================
_________________________________ test_sct_process_segmentation_check_normalize_PAM50 __________________________________
Traceback (most recent call last):
  File "/mnt/c/Users/sb199/spinalcordtoolbox/testing/cli/test_cli_sct_process_segmentation.py", line 111, in test_sct_process_segmentation_check_normalize_PAM50
    assert row['MEAN(area)'] == pytest.approx('71.9688049386959')
AssertionError: assert '71.96880493869594' == 71.9688049386959
  comparison failed
  Obtained: 71.96880493869594
  Expected: 71.9688049386959
------------------------------------------------- Captured stderr call -------------------------------------------------
Compute shape analysis: 100%|################| 55/55 [00:00<00:00, 336.34iter/s]
Aggregating metrics: 100%|######################| 9/9 [00:04<00:00,  1.89iter/s]
=============================================== short test summary info ================================================
FAILED testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_check_normalize_PAM50 - Assert...
ERROR testing/cli/test_cli_sct_process_segmentation.py::test_sct_process_segmentation_no_checks - AssertionError: ass...
================================= 1 failed, 9 passed, 633 warnings, 1 error in 20.71s ==================================
~~~

</details>

**Review by sandrinebedard — COMMENTED** [review]
Looks good! thanks for the clean up!

**Comment by sandrinebedard** [comment]
I just looked at the code and it looks good! However, I cannot compare using sct_process_segmentation, looks like the `-normalize-PAM50 is not there, like it is not based on the other branch, would help to compare if I get the same output!

**Comment by joshuacwnewton** [comment]
> When I run this test, this is what I get an assertion error:

Ahh, good to know! It looks like, then, there are slightly different outputs on different OSs. And ahhhhh, I see the problem here. The test is comparing strings!! So, `pytest.approx` doesn't even work, hehe. 

I'll fixup commit [b2befaa](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4013/commits/b2befaac72a5396a054c57cca264bca4eeb704f3) to add `float` calls, then rebase.

>  just looked at the code and it looks good! However, I cannot compare using sct_process_segmentation, looks like the `-normalize-PAM50 is not there, like it is not based on the other branch, would help to compare if I get the same output!

That's strange! I definitely tried to base it off of `sb/3733-bring-metrics-to-pam50`:

<details>

image
</details>

Ahhh, wait. I forgot to update my local copy of `sb/3773-bring-metrics-to-pam50` before creating the branch. My apologies! I'll fix everything up right now.

**Review by sandrinebedard — APPROVED** [review]
From your branch:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sb199/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sb199/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



656 | 9 |   | 45.83822131640725 | 0.0 | 17.04317263044791 | 0.0 | 17.90740050594679
-- | -- | -- | -- | -- | -- | -- | --
657 | 9 |   | 47.173496171356426 | 0.0 | 14.495592091105095 | 0.0 | 18.11240237284898
658 | 9 |   | 47.61984543005585 | 0.0 | 12.02341805124678 | 0.0 | 18.313542113563518
659 | 9 |   | 46.51057489531817 | 0.0 | 9.683205385486342 | 0.0 | 18.50792313344966




</body>

</html>


From before:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sb199/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sb199/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



656 | 9 |   | 45.83822131640725 | 0.0 | 17.04317263044791 | 0.0 | 17.90740050594679
-- | -- | -- | -- | -- | -- | -- | --
657 | 9 |   | 47.173496171356426 | 0.0 | 14.495592091105095 | 0.0 | 18.11240237284898
658 | 9 |   | 47.61984543005585 | 0.0 | 12.02341805124678 | 0.0 | 18.313542113563518
659 | 9 |   | 46.51057489531817 | 0.0 | 9.683205385486342 | 0.0 | 18.50792313344966



</body>

</html>


Everything looks the same! We can merge!

**Pull request merged**
