### PR TITLE
Port changes from SCT Course 2023 Google Slides to the web tutorials

### LINKED ISSUE #4236: Move "Labeling" section outside of "Registration" in the web tutorials
Currently vertebral labeling is inside registration to template:

image

given that ppl might want to label vert/discs without doing reg to template, i suggest moving this section to headings1

collateral benefits: the labeling convention will be more visible (https://github.com/spinalcordtoolbox/PAM50/pull/27#issuecomment-1747417942)

### LINKED ISSUE #4248: Update SCT course for new spinal levels
Alongside https://github.com/spinalcordtoolbox/PAM50/pull/18, update the SCT course to reflect the change. Any reference to a "separate" spinal level folder. Also make sure to remove the term "probabilistic" spinal levels.

### LINKED ISSUE #4263: Rework the segmentation section of the tutorials/course to prioritize `sct_deepseg_sc`
During the 2023-10-05 SCT meeting, we discussed reworking the segmentation section to no longer start with `sct_propseg`. 

The rationale for this is:

- People will often start with what works and not read any further -- may miss that `sct_deepseg_sc` works better.
- Saving time (~10m) during the course to make room for new material that has been added.

The only downside is that the trial-and-error segmentation steps (T1w leakage for sct_propseg, fixed by sct_deepseg_sc) was very good as an introduction, easing people into the process of using SCT. So, we would lose this nicely-designed section. :thinking:

### LINKED ISSUE #4264: Consider ordering shape analysis *before* registration to template
That way, the progression of the tutorials would go:

1. CSA pipeline
    i. Segmentation
    ii. Vertebral labeling
    iii. Shape analysis (no PAM50 template used)
2. Registration pipeline
    i. Registration to PAM50 template
    ii. Multimodal registration
    iii. Lumbar registration

Benefits:

1. We can use CSA calculation as motivation for segmentation/vertebral labeling
2. People can learn to compute CSA/shape metrics without needing to learn the cumbersome registration first
3. The initial section (seg -> label -> CSA) can act as a very straightforward "intro to SCT" section

### LINKED ISSUE #4275: Low quality gray matter based registration on SCT course 2023
Going through the slides, on the GM-based registration:

image

I noticed that the registration result is pretty bad:

anim

I am wondering if something has changed in SCT that made results worst compared to the previous SCT course in 2021. Or were results the same in 2021? How can we "easily" check that?

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

This PR compiles all of the changes from the SCT Course slides and adds them to the web tutorials. Namely:

- Shortening the Segmentation section to prioritize `sct_deepseg_sc` and `sct_deepseg`. 
- Moving vertebral labeling and shape analysis before registration.
- Updating the "vertebral labeling" conventions pages.
- Updating the fMRI spinal level section to reflect the changes to the PAM50 template.
- Updating the command used in the GM-informed registration section.

Associated changes have been made to related repos, too:

- The `doc-figures` repo has been updated with new/modified figures where needed.
- An associated `sct_tutorial_data` release (r20231129) also reflects some of these changes (though most of the necessary changes to the dataset had already been made in the SCT Course 2023 release).

I've also used this opportunity to cross-link any tutorials that rely on results from past tutorials, in the hopes that the connected-ness is made clearer for users.

I've tried my best to update wording wherever possible (to reflect the new order of the tutorials). However, given how much has been written, it's very possible that I've missed a reference or two, and the flow may not make sense. So, if you see anything that feels "off" or outdated, please comment!

## Linked issues

Fixes #4236.
Fixes #4248.
Fixes #4263.
Fixes #4264.
Fixes #4275.

### CODE REVIEW

**Comment by jcohenadad** [comment]
I suggest moving the fMRI section (and call it "Functional MRI") at the same level as the dMRI section:
image

More and more people are into fMRI these days.

**Review by jcohenadad — COMMENTED** [review]
Thank you so much for doing this massive update on the tutorials @joshuacwnewton 🙏 !! This is excellent. I only have minor comments added directly in the PR discussion thread.

**Comment by joshuacwnewton** [comment]
Thank you for the feedback! I very much agree with your comments, and I'll make the changes accordingly.

> Is it normal that the image does not show up?

To address this specifically: No, this is not normal! It looks like the spinal level tutorial re-used an image from the PAM50 page (and said image was deleted in https://github.com/spinalcordtoolbox/doc-figures/commit/394d1af6e69ec8f18a067f4c568814a246662907).

I re-added a new `spinal_levels_illustration.png` image to the doc-figures repo, but I put it in the fMRI category, while the old URL still points to `/pam50/`. So, it's just a matter of updating the image URL. :)

**Review by mguaypaq — APPROVED** [review]
Thanks for this huge improvement!

**Pull request merged**
