### PR TITLE
Add support for ITK-Snap + multiple viewers to `display_viewer_syntax`

### LINKED ISSUE #3745: Add support for ITK-Snap in the `display_viewer_syntax` function
> **Note:** This has already been discussed in SCT meetings -- I'm just creating an issue for documentation purposes.

Our current `display_viewer_syntax` function only provides support for fslview/fsleyes. But, these tools aren't available on Windows.

Now that we (experimentally) support a native installation of SCT on Windows, it would be nice to also output syntax for ITK-SNAP, so that Windows users can view output images, too.

Note that ITK-SNAP is also supported on macOS/Linux, and it's possible that a user may have both FSLeyes and ITK-SNAP installed, so we may want to consider displaying the syntax for all available viewers.

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [ ] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [ ] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [ ] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

This PR provides `display_viewer_syntax` output more suitable to Windows users by outputting commands for ITK-Snap (rather than leaning so heavily on FSL-based viewers).

<details>
<summary> Some sample images </summary>

image

image

image

image

</details>

Some small refactors were needed to support both Windows (`itk-snap.exe`) and Linux/macOS (`itksnap`), especially given that Linux/macOS users could theoretically have multiple viewers installed, and we don't want to preference one or the other.

## Linked issues

Fixes #3745.

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
I'd like to add some a for `display_viewer_syntax` just to make sure it's behaving as expected after the refactor, since I think the logic is just complicated enough to warrant it (and if anything went wrong, it would be a quiet visual issue that would be hard to catch otherwise).

As soon as I'm done that, I'll mark this as ready for review.

**Review by RignonNoel — APPROVED** [review]
Nice work, I like the little condition to change the text depending if you have one or multiple options available ;)

I know it's a bit more generic, but maybe it would have been nice to split the logic in subpart for readibility like `get_available_viewers()`, `generate_viewer_command(viewer, options)` & `display_viewer_syntax(...)`. I'm a bit architecture nazi and little function enhance greatly the time of debuging

**Comment by joshuacwnewton** [comment]
> I know it's a bit more generic, but maybe it would have been nice to split the logic in subpart for readibility like `get_available_viewers()`, `generate_viewer_command(viewer, options)` & `display_viewer_syntax(...)`.

Thank you for the suggestion! I've tried incorporating your idea into 9dff2da and 638d55a, and I think it's a bit cleaner now? :)

**Review by RignonNoel — APPROVED** [review]
Good job! I think it's more easy to read and rampup for future enhancement

**Pull request merged**
