### PR TITLE
Remove `round_and_clip` function from `centerline/core.py`

### LINKED ISSUE #4029: Remove the `round_and_clip` function from `centerline/core.py`
In https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4026#discussion_r1096182595, some confusion arose due to the `round_and_clip` function, which calls `np.round` and `np.clip`, but adds some subtle behavior changes, most notable a `-1`.

On further inspection, though, this function's existence is confusing, as there's not really any added benefit/functionality beyond the underlying `numpy` functions themselves:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0f228da127cc78408462b824624564ea7e09a7ba/spinalcordtoolbox/centerline/core.py#L275-L278

Why not just call `np.round` and `np.clip` individually when needed?

Additionally, `round_and_clip` is only truly called twice, both in the context of `centerline/core.py`, so its usage isn't even widespread:

image

Given that it's a source of confusion, I would suggest to get rid of it entirely?

### PR DESCRIPTION
**Pull request by co-decode**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [x] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
The issue discussed removing the round_and_clip function from centerline/core.py
I have removed this function and refactored its usage elsewhere in this file by using np.clip and np.round individually
The function only appeared again in testing/api/test_centerline.py, which I have also removed.

Should a replacement test be added?

Also, be aware that I've commented out the unused imports to test_centerline.py. The linter (flake8) caused me to do this.

## Linked issues
Resolves #4029

### CODE REVIEW

**Comment by mguaypaq** [comment]
> The function only appeared again in testing/api/test_centerline.py, which I have also removed.
>
> Should a replacement test be added?

Thanks for removing the test. It was specifically just a sanity check for `round_and_clip`, so it has no reason to exist anymore. Since the code now just uses `np.round` and `np.clip` is a straightforward way, I'm happy to rely on Numpy's quality checks.

> Also, be aware that I've commented out the unused imports to test_centerline.py. The linter (flake8) caused me to do this.

Yes, that's fine. For now, the linter is configured to only run on files that get modified, so that we can gradually bring the entire code base up to its standards over time, by fixing files when we touch them.

In this case, it would be better to simply remove (rather than commenting out) the unused imports. On my computer, the linter also complains about an unused variable somewhere else in the same file. I've added a commit to fix this in the `cdc/4029-remove-round-and-clip` branch in this repository, and I'll open a pull request in your fork to include it in this PR. (Maybe there's a simpler way to do this? I don't know.)

**Review by mguaypaq — APPROVED** [review]
This change looks good, thanks! As mentioned above, I've suggested adding one more commit to properly fix the linting errors in `test_centerline.py`. I'll mark this "approved" so that we can quickly merge the PR once that commit is added.

**Comment by joshuacwnewton** [comment]
> I've added a commit to fix this in the `cdc/4029-remove-round-and-clip` branch in this repository, and I'll open a pull request in your fork to include it in this PR. (Maybe there's a simpler way to do this? I don't know.)

It should be possible to push directly to the fork's branch, assuming @co-decode has left the "[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" checkbox checked. (See the link for more details.)

**Comment by mguaypaq** [comment]
Good point, @joshuacwnewton! I just pushed the extra commit directly to @co-decode's fork (which Github recognized as enough to close the secondary PR I opened, neat!), so now we can just wait for tests to pass and merge this (original) PR.

**Pull request merged**
