### PR TITLE
add sct_citation script

### LINKED ISSUE #2412: Generate SCT citation function
Create a function *sct_citation* to output the bibtex citation in the terminal.
https://github.com/neuropoly/spinalcordtoolbox#citing-spinalcordtoolbox

### PR DESCRIPTION
**Pull request by RignonNoel**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) to this PR
- [ ] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
Added a new script `sct_citation` to help people output the BibTex reference of SCT.

It was a great opportunity for me to make sure I understand all the steps to create a new scripts and how to use commands directly from the doc.

 - Added a unit test
 - Updated documentation

## Linked issues
Fixes #2412

### CODE REVIEW

**Comment by RignonNoel** [comment]
@joshuacwnewton Is it possible for a script to remove the header output ?

```
--
Spinal Cord Toolbox (git-feature-sct_citation_script-9fd17d71d4a0ed1869802561bd770025f1d60613)

sct_citation
--

[... script output ...]
```

It would be nice for two reasons:

 - to allow people listening the output and do some automation (could be interesting for a lot of scripts)
 - to replace the citation already in the documentation by the generated output of this new script

**Comment by jcohenadad** [comment]
@RignonNoel thank you so much for working on this. Re-reading the issue and context, i am not 100% convinced that adding that CLI is worth it. Few considerations:
- adding another CLI adds 'noise' for our users (ie: there is already a lot of CLI functions that they need to learn about, so it could be overwhelming to see a list of many CLIs)
- not having this function 'forces' them to go on https://spinalcordtoolbox.com/, where the citation is listed, alongside other citations (to sct_deepseg_sc, PAM50, etc.), so it gives them the opportunity to not _only_ cite SCT main paper, but also other papers from our group
- going in the website, they will be exposed to other useful stuff (tutorials, etc.)

**Comment by RignonNoel** [comment]
@jcohenadad Honestly I tough the same thing but since the issue didn't had a lot of details maybe @alexfoias would like to explain what was the initial idea so we can make sure the initial "need" is answered correctly ?

**Comment by alexfoias** [comment]
My initial idea was to replace the reference from https://spinalcordtoolbox.com/user_section/citing_sct.html#main-reference with a CLI command instead of going on the website. I see your motivation to be able to drive more traffic without having it. Maybe we can keep both since @RignonNoel spent time implementing it ?

**Comment by jcohenadad** [comment]
> Maybe we can keep both since @RignonNoel spent time implementing it ?

That should not be an argument for the decision.

**Comment by joshuacwnewton** [comment]
Just to chime in, I think I agree with @jcohenadad's suggestions, and I would support closing both this PR and the original issue.

Thank you for taking the time to open this PR in the first place, though!

----

> Honestly I tough the same thing but since the issue didn't had a lot of details 

Perhaps in the future, for issues that don't contain many details, we could discuss further on the issue before opening a PR? That way, we can save putting the effort if we decide that a feature is no longer wanted. :sweat_smile:

**Pull request closed without merging**
