### PR TITLE
Fix broken `-v 2` case by making sure `fname_res_ctr` exists prior to resampling

### LINKED ISSUE #3970: `sct_deepseg_lesion` with  `-v 2` fails with `FileNotFoundError`
> Hm, `sct_deepseg_lesion` with  `-v 2` still fails:
> 
> ```
> $ sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -r 0 -v 2
> .
> .
> .
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_deepseg_lesion.py", line 173, in <module>
>     main(sys.argv[1:])
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_deepseg_lesion.py", line 148, in main
>     im_seg, im_labels_viewer, im_ctr = deep_segmentation_MSlesion(im_image, contrast_type, ctr_algo=ctr_algo, ctr_file=manual_centerline_fname,
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/deepseg_/lesion.py", line 235, in deep_segmentation_MSlesion
>     resampling.resample_file(fname_res_ctr, fname_res_ctr, initial_resolution,
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/resampling.py", line 157, in resample_file
>     nii = nib.load(fname_data)
>   File "/usr/local/lib/sct/python/envs/venv_sct/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
>     raise FileNotFoundError(f"No such file or no access: '{filename}'")
> FileNotFoundError: No such file or no access: 'image_in_RPI_res_ctr.nii'  
> ```
> 
> <details><summary>Full output</summary>
> 
> ```
> $ sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -r 0 -v 2                                                 
> 
> --
> Spinal Cord Toolbox (git-master-812a8e00bd8862c3c9f2d099e24e0143a5337976*)
> 
> sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -r 0 -v 2
> --
> 
> 
> Method:
> 	Centerline algorithm: svm
> 	Assumes brain section included in the image: True
> 
> Loaded sub-mon001_ses-M0_T2w.nii.gz (/Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz) orientation LPI shape (63, 320, 320)
> Image header specifies datatype 'int16', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.
> Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg)
> Reorient the image to RPI, if necessary...
> Affine matrix: 
> [[-7.99823999e-01 -8.07573553e-03  1.48307504e-02  2.15871563e+01]
>  [-5.79589698e-03  7.91190743e-01  1.18252650e-01 -1.22633926e+02]
>  [ 1.58612058e-02 -1.18118845e-01  7.91072965e-01 -2.36985718e+02]
>  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
> Saving image to image_in_RPI_res.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg/image_in_RPI_res.nii) orientation RPI shape (101, 512, 320)
> 
> Finding the spinal cord centerline...
> Loaded image_in_RPI_res.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg/image_in_RPI_res.nii) orientation RPI shape (101, 512, 320)
> Detecting the spinal cord using OptiC
> Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133437.036951-ltfha7v6)
> Saving image to img_rpi_uint16.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133437.036951-ltfha7v6/img_rpi_uint16.nii) orientation RPI shape (101, 512, 320)
> Loaded img_rpi_uint16_optic_ctr.hdr (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133437.036951-ltfha7v6/img_rpi_uint16_optic_ctr.hdr) orientation RPI shape (101, 512, 320)
> 
> Cropping the image around the spinal cord...
> Normalizing the intensity...
> Image header specifies datatype 'float64', but array is of type 'float32'. Header metadata will be overwritten to use 'float32'.
> Saving image to image_in_RPI_res_norm.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg/image_in_RPI_res_norm.nii) orientation RPI shape (48, 48, 320)
> load data...
> Affine matrix: 
> [[-4.98900115e-01 -5.04733482e-03  1.48307504e-02  2.15871563e+01]
>  [-3.61526245e-03  4.94494200e-01  1.18252650e-01 -1.22633926e+02]
>  [ 9.89362318e-03 -7.38242790e-02  7.91072965e-01 -2.36985718e+02]
>  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
> 
> Segmenting the MS lesions using deep learning on 3D patches...
> Loaded image_in_RPI_res_norm_resampled3d.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg/image_in_RPI_res_norm_resampled3d.nii) orientation RPI shape (48, 48, 512)
> Image header specifies datatype 'uint8', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.
> Saving image to image_in_RPI_res_norm_resampled3d_lesionseg.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg/image_in_RPI_res_norm_resampled3d_lesionseg.nii) orientation RPI shape (48, 48, 512)
> load data...
> Affine matrix: 
> [[-4.98900115e-01 -5.04733482e-03  9.26921889e-03  2.15871563e+01]
>  [-3.61526245e-03  4.94494200e-01  7.39079043e-02 -1.22633926e+02]
>  [ 9.89362318e-03 -7.38242790e-02  4.94420588e-01 -2.36985718e+02]
>  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
> Loaded image_in_RPI_res_norm_resampled3d_lesionseg_resampled2d.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221201133429.700388-aijziglg/image_in_RPI_res_norm_resampled3d_lesionseg_resampled2d.nii) orientation RPI shape (48, 48, 320)
> 
> Reassembling the image...
> Saving image to /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_res_RPI_seg.nii.gz orientation RPI shape (101, 512, 320)
> Resampling the segmentation to the original image resolution...
> load data...
> Affine matrix: 
> [[-4.98900115e-01 -5.04733482e-03  1.48307504e-02  2.15871563e+01]
>  [-3.61526245e-03  4.94494200e-01  1.18252650e-01 -1.22633926e+02]
>  [ 9.89362318e-03 -7.38242790e-02  7.91072965e-01 -2.36985718e+02]
>  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
> Loaded /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_RPI_seg.nii.gz orientation RPI shape (63, 320, 320)
> load data...
> Traceback (most recent call last):
>   File "/usr/local/lib/sct/python/envs/venv_sct/lib/python3.8/site-packages/nibabel/loadsave.py", line 42, in load
>     stat_result = os.stat(filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'image_in_RPI_res_ctr.nii'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_deepseg_lesion.py", line 173, in <module>
>     main(sys.argv[1:])
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_deepseg_lesion.py", line 148, in main
>     im_seg, im_labels_viewer, im_ctr = deep_segmentation_MSlesion(im_image, contrast_type, ctr_algo=ctr_algo, ctr_file=manual_centerline_fname,
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/deepseg_/lesion.py", line 235, in deep_segmentation_MSlesion
>     resampling.resample_file(fname_res_ctr, fname_res_ctr, initial_resolution,
>   File "/usr/local/lib/sct_latest/spinalcordtoolbox/resampling.py", line 157, in resample_file
>     nii = nib.load(fname_data)
>   File "/usr/local/lib/sct/python/envs/venv_sct/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
>     raise FileNotFoundError(f"No such file or no access: '{filename}'")
> FileNotFoundError: No such file or no access: 'image_in_RPI_res_ctr.nii'                    
> ```
> 
> </details>

_Originally posted by @valosekj in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3956#issuecomment-1334192141_

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

When `sct_deepseg_lesion` is called with `-v 2`, an error is thrown, because `resample_file` is called on the `fname_res_ctr` filename, but that file that doesn't exist.

I tried to infer where exactly this file was supposed to have been created:

- `fname_res_ctr` is the result of `fname_orient` combined with a `_ctr` (centerline) suffix.
   https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6ee19076472c7e42da1e15b4483ff0720772df27/spinalcordtoolbox/deepseg_/lesion.py#L234
- Because the filename implies a centerline file created from `fname_orient`, this clearly seems to me to be:
   https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6ee19076472c7e42da1e15b4483ff0720772df27/spinalcordtoolbox/deepseg_/lesion.py#L157-L163
- So, I've saved `im_ctl` using the filename expected later on in the function.

## Linked issues

Fixes #3970.

### CODE REVIEW

**Review by valosekj — COMMENTED** [review]
Thank you for the proposed workaround @joshuacwnewton! It looks logical!

However, I am a bit confused about how the verbose flag is used in this script. I thought that verbosity controls the number of warnings and errors printed to the CLI. But it seems that the verbosity also influences which temporary files will be created. Shouldn't this be controlled by the `-r` flag?

**Comment by joshuacwnewton** [comment]
> However, I am a bit confused about how the verbose flag is used in this script. I thought that verbosity controls the number of warnings and errors printed to the CLI. But, it this case, it seems that the verbosity also influences which temporary files will be created. Shouldn't this be controlled by the `-r` flag?

You're right, it is a bit weird here for `-v 2` to result in an extra file being created.

This code was written before I joined NeuroPoly, so I can only guess as to the rationale here, but my best idea is:

- `-v 2` is used to debug scripts -- it not only controls logging messages, but also stuff like optional matplotlib plots.
- `-r 0` is meant to preserve temporary files used in (mandatory) intermediate processing steps.
- From what I can tell, the generated file is an optional file used purely for debugging purposes. 
- So, I think that's why `-v 2` was chosen, rather than `-r 0`.

**Comment by valosekj** [comment]
> > However, I am a bit confused about how the verbose flag is used in this script. I thought that verbosity controls the number of warnings and errors printed to the CLI. But, it this case, it seems that the verbosity also influences which temporary files will be created. Shouldn't this be controlled by the `-r` flag?
> 
> You're right, it is a bit weird here for `-v 2` to result in an extra file being created.
> 
> This code was written before I joined NeuroPoly, so I can only guess as to the intended purpose here, but my best idea is:
> 
> * `-v 2` is used to debug scripts -- it not only controls logging messages, but also stuff like optional matplotlib plots.
> * `-r 0` is meant to preserve temporary files used in (mandatory) intermediate processing steps.
> * From what I can tell, the generated file is an optional file used purely for debugging purposes.
> * So, I think that's why `-v 2` was chosen, rather than `-r 0`.

Okay. Thank you for the explanation!
From my side, the PR fixes what it should fix. And since the refactoring of the script is beyond this PR, we can probably merge it.

**Review by mguaypaq — APPROVED** [review]
Further evidence that this is the right file:
* Up until [this commit, line 145](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/95aab66283b0cf442cd398f3a50d82d1cded547a#diff-b419096d7d749d840ab7a83c93deb41fd290394851642de234f60b58a6eb86b4L145), the `find_centerline()` function used to return the centerline through a saved file.
* A few lines up, [at line 58](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/95aab66283b0cf442cd398f3a50d82d1cded547a#diff-b419096d7d749d840ab7a83c93deb41fd290394851642de234f60b58a6eb86b4L58), it used the suffix `_ctr` for this saved file.

**Pull request merged**
