### PR TITLE
Add `manual-correction` to `download.py` to make downloading easier for the SCT Course

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

Right now, the manual correction scripts exist outside of the SCT repo, for reasons outlined in:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3353

However, this makes accessing the manual correction script difficult (requiring either a `git clone` or a `wget`/`curl` call).

So, similarly to https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4271, we make use of `sct_download_data` as a download manager, to ease the process of downloading a URL + unzipping it to the correct folder.

Additionally, I've re-added the separate "Course" download category, which should signal to users that manual correction is intended to be used within the context of the SCT course.

## Linked issues

Fixes https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit?disco=AAAA_SxrQH8.

### CODE REVIEW

**Review by valosekj — APPROVED** [review]
Nice workaround on how to download the `manual-correction` repo, @joshuacwnewton!

Tested and working fine!

```console
$ cd $SCT_DIR/
$ git fetch
$ git checkout jn/make-course-file-downloading-easier
$ cd ~
$ sct_download_data -d manual-correction -o manual-correction
$ cd manual-correction
$ source ${SCT_DIR}/python/etc/profile.d/conda.sh
$ conda activate venv_sct
$ python manual_correction.py -h
```

**Comment by joshuacwnewton** [comment]
Side note: This also allows us to avoid `git clone` creating nested git repositories, which can be a little funky to work with sometimes.

**Comment by valosekj** [comment]
This PR makes me think about the [manual-correction](https://github.com/spinalcordtoolbox/manual-correction) repo from a broader perspective again. Making it part of SCT (as originaly proposed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3353) would simplify its download. And potentially also solve the issue with two conda envs (one for fsleyes, second for manual_correction.py; [slide 148](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.p137))?

**Comment by joshuacwnewton** [comment]
That was exactly my thinking, too... definitely something to consider!

**Pull request merged**
