### PR TITLE
Add possiblity for text output for sct-compute-snr

### LINKED ISSUE #3453: Add possibility for output TXT
**Feature justification**

Function `sct_compute_snr` outputs results in the Terminal:
~~~
julien-macbook:~/temp/20210712_gmchallenge/data_processed/9418 $ sct_compute_snr -i data_concat.nii.gz -method mult -m data1_crop_wmseg_erode.nii.gz 

--
Spinal Cord Toolbox (git-jca/sb/3063-csa-measure-from-pmj-05976283f121899e8903e8bb8222dce004940236)

sct_compute_snr -i data_concat.nii.gz -method mult -m data1_crop_wmseg_erode.nii.gz
--


SNR_mult = 20.003156441135573
~~~

When implementing pipelines, one needs to access this Terminal output and use it for making statistics. This currently requires an ugly regex manipulation to access the float value from stdout. 

**Describe the solution you'd like**

A new flag `-o` where user could indicate a TXT file name where results are output. The TXT file would only contain the number, so it can conveniently be opened by any Python script.

**Additional context**

The need for this feature came up while working on the [GM challenge project](https://github.com/sct-pipeline/gm-challenge).

### PR DESCRIPTION
**Pull request by santoshdvc**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [ ] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [ ] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

I have changed the `sct-compute-snr` file by adding an function for text file output. I have added the optional argument  `-o` with string argument. The output number of `snr_roi` is saved in TXT.
```
-o <file/path name>
```

## Linked issues

Resolves #3453

### CODE REVIEW

**Comment by jcohenadad** [comment]
Thank you so much for taking on this @santoshdvc 🙏

When pulling your branch I noticed that the mode of many files changed (and Github does not show it):

<details><summary>Terminal output</summary>

```console
julien-macbook:~/code/sct $ git checkout -b santoshdvc-add-text-output master
Switched to a new branch 'santoshdvc-add-text-output'
julien-macbook:~/code/sct $ git pull https://github.com/santoshdvc/spinalcordtoolbox.git add-text-output
remote: Enumerating objects: 231, done.
remote: Counting objects: 100% (231/231), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 158 (delta 73), reused 77 (delta 35), pack-reused 0
Receiving objects: 100% (158/158), 64.92 KiB | 1.47 MiB/s, done.
Resolving deltas: 100% (73/73), completed with 34 local objects.
From https://github.com/santoshdvc/spinalcordtoolbox
 * branch                add-text-output -> FETCH_HEAD
Updating 634670e4e..dfc9454c6
Fast-forward
 .github/workflows/test-batch-processing.yml                     |   2 +-
 batch_processing.sh                                             |   8 +-
 conftest.py                                                     |  10 +
 documentation/source/conf.py                                    |  11 +-
 documentation/source/index.rst                                  |  11 +-
 documentation/source/overview/concepts.rst                      |   3 +-
 .../source/overview/concepts/inspecting-results-qc-fsleyes.rst  |  82 ++++
 documentation/source/overview/concepts/pam50.rst                |  26 +-
 documentation/source/overview/concepts/quality-control.rst      |   8 -
 documentation/source/overview/concepts/warping-fields.rst       |  77 ++++
 documentation/source/tutorials/courses.rst                      |  32 --
 .../source/tutorials/pages/spinalcord_segmentation.rst          | 247 -----------
 documentation/source/tutorials/tutorials.rst                    |  16 -
 documentation/source/tutorials/video-tutorials.rst              |   6 -
 documentation/source/user_section/command-line.rst              |   6 -
 documentation/source/user_section/getting-started.rst           |   2 +-
 documentation/source/user_section/installation.rst              |   4 +-
 documentation/source/user_section/tutorials.rst                 |  63 +++
 documentation/source/user_section/tutorials/mtr-computation.rst |  14 +
 .../user_section/tutorials/mtr-computation/before-starting.rst  |  23 ++
 .../user_section/tutorials/mtr-computation/computing-mtr.rst    |  23 ++
 .../tutorials/mtr-computation/coregistering-mt0-mt1.rst         |  34 ++
 .../user_section/tutorials/registering-additional-contrasts.rst |  18 +
 .../applying-the-warping-fields.rst                             |  26 ++
 .../registering-additional-contrasts/before-starting.rst        |  21 +
 .../registering-additional-contrasts/creating-a-mask.rst        |  26 ++
 .../registration-1-reusing-warping-fields.rst                   |  41 ++
 .../registration-2-direct-registration.rst                      |  29 ++
 .../spinalcord-segmentation.rst                                 |  24 ++
 .../source/user_section/tutorials/shape-metric-computation.rst  |  23 ++
 .../tutorials/shape-metric-computation/angle-ap-rl.csv          |   3 +
 .../tutorials/shape-metric-computation/before-starting.rst      |  17 +
 .../tutorials/shape-metric-computation/csa-averaged.rst         |  23 ++
 .../tutorials/shape-metric-computation/csa-perlevel.rst         |  24 ++
 .../tutorials/shape-metric-computation/csa-perslice.rst         |  23 ++
 .../tutorials/shape-metric-computation/csa_c3c4.csv             |   2 +
 .../tutorials/shape-metric-computation/csa_perlevel.csv         |   3 +
 .../tutorials/shape-metric-computation/csa_perslice.csv         |   7 +
 .../shape-metric-computation/other-shape-metrics-1.csv          |   3 +
 .../shape-metric-computation/other-shape-metrics-2.csv          |   3 +
 .../tutorials/shape-metric-computation/other-shape-metrics.rst  |  22 +
 .../shape-metric-computation/verifying-correctness.rst          |  18 +
 .../source/user_section/tutorials/spinalcord-segmentation.rst   |  24 ++
 .../tutorials/spinalcord-segmentation/before-starting.rst       |  19 +
 .../tutorials/spinalcord-segmentation/choosing-an-algorithm.rst |   6 +
 .../tutorials/spinalcord-segmentation/contrasts.rst             |  10 +
 .../fixing-failed-sct_propseg-segmentations.rst}                |  34 +-
 .../spinalcord-segmentation/sct_deepseg_sc-example-t1.rst       |  27 ++
 .../tutorials/spinalcord-segmentation/sct_deepseg_sc.rst        |  20 +
 .../spinalcord-segmentation/sct_propseg-example-t1.rst          |  27 ++
 .../spinalcord-segmentation/sct_propseg-example-t2.rst          |  22 +
 .../tutorials/spinalcord-segmentation/sct_propseg.rst           |  24 ++
 .../source/user_section/tutorials/template-registration.rst     |  20 +
 .../applying-the-registration-algorithm.rst                     |  31 ++
 .../template-registration/applying-the-warping-fields.rst       |  27 ++
 .../tutorials/template-registration/before-starting.rst         |  24 ++
 .../template-registration/customizing-registration.rst          |  90 ++++
 .../template-registration/sct_register_to_template.rst          |  22 +
 .../source/user_section/tutorials/vertebral-labeling.rst        |  21 +
 .../vertebral-labeling/applying-the-labeling-algorithm.rst      |  28 ++
 .../tutorials/vertebral-labeling/before-starting.rst            |  21 +
 .../extracting-specific-labels-for-registration.rst             |  26 ++
 .../vertebral-labeling/how-many-labels-for-registration.rst     |  17 +
 .../tutorials/vertebral-labeling/labeling-conventions.rst       |  17 +
 .../tutorials/vertebral-labeling/manual-labeling-all-labels.rst |  31 ++
 .../tutorials/vertebral-labeling/manual-labeling-c2c3.rst       |  29 ++
 .../tutorials/vertebral-labeling/sct_label_vertebrae.rst        |  23 ++
 setup.cfg                                                       |   2 +
 setup.py                                                        |   1 -
 spinalcordtoolbox/reports/qc.py                                 |   2 +-
 spinalcordtoolbox/reports/slice.py                              |  10 +-
 spinalcordtoolbox/scripts/sct_compute_snr.py                    |  23 +-
 spinalcordtoolbox/scripts/sct_label_vertebrae.py                |  11 +-
 spinalcordtoolbox/scripts/sct_register_multimodal.py            |  34 +-
 spinalcordtoolbox/scripts/sct_testing.py                        | 611 ----------------------------
 testing/test_sct_analyze_lesion.py                              |  41 --
 testing/test_sct_analyze_texture.py                             |  54 ---
 testing/test_sct_apply_transfo.py                               |  97 -----
 testing/test_sct_compute_ernst_angle.py                         |  42 --
 testing/test_sct_compute_hausdorff_distance.py                  |  54 ---
 testing/test_sct_compute_mscc.py                                |  47 ---
 testing/test_sct_compute_mtr.py                                 |  33 --
 testing/test_sct_compute_snr.py                                 |  34 --
 testing/test_sct_concat_transfo.py                              |  32 --
 testing/test_sct_convert.py                                     |  42 --
 testing/test_sct_create_mask.py                                 |  36 --
 testing/test_sct_crop_image.py                                  |  59 ---
 testing/test_sct_deepseg_gm.py                                  |  54 ---
 testing/test_sct_deepseg_lesion.py                              |  34 --
 testing/test_sct_deepseg_sc.py                                  |  31 --
 testing/test_sct_denoising_onlm.py                              |  38 --
 testing/test_sct_detect_pmj.py                                  |  68 ----
 testing/test_sct_dice_coefficient.py                            |  58 ---
 testing/test_sct_dmri_compute_bvalue.py                         |  30 --
 testing/test_sct_dmri_compute_dti.py                            |  30 --
 testing/test_sct_dmri_concat_b0_and_dwi.py                      |  29 --
 testing/test_sct_dmri_concat_bvals.py                           |  30 --
 testing/test_sct_dmri_concat_bvecs.py                           |  30 --
 testing/test_sct_dmri_moco.py                                   |  80 ----
 testing/test_sct_dmri_separate_b0_and_dwi.py                    |  60 ---
 testing/test_sct_dmri_transpose_bvecs.py                        |  30 --
 testing/test_sct_extract_metric.py                              |  50 ---
 testing/test_sct_flatten_sagittal.py                            |  40 --
 testing/test_sct_fmri_compute_tsnr.py                           |  31 --
 testing/test_sct_fmri_moco.py                                   |  30 --
 testing/test_sct_get_centerline.py                              |  43 --
 testing/test_sct_image.py                                       |  96 -----
 testing/test_sct_label_utils.py                                 |  58 ---
 testing/test_sct_label_vertebrae.py                             |  33 --
 testing/test_sct_maths.py                                       |  35 --
 testing/test_sct_merge_images.py                                |  33 --
 testing/test_sct_process_segmentation.py                        |  40 --
 testing/test_sct_propseg.py                                     |  68 ----
 testing/test_sct_qc.py                                          |  36 --
 testing/test_sct_register_multimodal.py                         |  71 ----
 testing/test_sct_register_to_template.py                        |  97 -----
 testing/test_sct_resample.py                                    |  63 ---
 testing/test_sct_smooth_spinalcord.py                           |  33 --
 testing/test_sct_straighten_spinalcord.py                       |  35 --
 testing/test_sct_warp_template.py                               |  33 --
 unit_testing/batch_processing/test_batch_processing.py          |  61 +--
 unit_testing/cli/test_cli.py                                    |   1 -
 unit_testing/cli/test_cli_sct_analyze_lesion.py                 |  18 +-
 unit_testing/cli/test_cli_sct_analyze_texture.py                |  24 +-
 unit_testing/cli/test_cli_sct_apply_transfo.py                  |  40 +-
 unit_testing/cli/test_cli_sct_compute_ernst_angle.py            |  19 +-
 unit_testing/cli/test_cli_sct_compute_hausdorff_distance.py     |  24 +-
 unit_testing/cli/test_cli_sct_compute_mscc.py                   |  21 +-
 unit_testing/cli/test_cli_sct_compute_mtr.py                    |  16 +-
 unit_testing/cli/test_cli_sct_compute_snr.py                    |  17 +-
 unit_testing/cli/test_cli_sct_concat_transfo.py                 |  17 +-
 unit_testing/cli/test_cli_sct_convert.py                        |  19 +-
 unit_testing/cli/test_cli_sct_create_mask.py                    |  23 +-
 unit_testing/cli/test_cli_sct_crop_image.py                     |  24 +-
 unit_testing/cli/test_cli_sct_deepseg_gm.py                     |  20 +-
 unit_testing/cli/test_cli_sct_deepseg_lesion.py                 |  16 +-
 unit_testing/cli/test_cli_sct_deepseg_sc.py                     |  27 +-
 unit_testing/cli/test_cli_sct_denoising_onlm.py                 |  14 +
 unit_testing/cli/test_cli_sct_detect_pmj.py                     |  51 ++-
 unit_testing/cli/test_cli_sct_dice_coefficient.py               |  23 +-
 unit_testing/cli/test_cli_sct_dmri_compute_bvalue.py            |  16 +-
 unit_testing/cli/test_cli_sct_dmri_compute_dti.py               |  16 +-
 unit_testing/cli/test_cli_sct_dmri_concat_b0_and_dwi.py         |  19 +-
 unit_testing/cli/test_cli_sct_dmri_concat_bvals.py              |  16 +-
 unit_testing/cli/test_cli_sct_dmri_concat_bvecs.py              |  16 +-
 unit_testing/cli/test_cli_sct_dmri_moco.py                      |  65 ++-
 unit_testing/cli/test_cli_sct_dmri_separate_b0_and_dwi.py       |  30 +-
 unit_testing/cli/test_cli_sct_dmri_transpose_bvecs.py           |  16 +-
 unit_testing/cli/test_cli_sct_extract_metric.py                 |  22 +-
 unit_testing/cli/test_cli_sct_flatten_sagittal.py               |  16 +-
 unit_testing/cli/test_cli_sct_fmri_compute_tsnr.py              |  16 +-
 unit_testing/cli/test_cli_sct_fmri_moco.py                      |  16 +-
 unit_testing/cli/test_cli_sct_get_centerline.py                 |  23 +-
 unit_testing/cli/test_cli_sct_image.py                          |  74 +++-
 unit_testing/cli/test_cli_sct_label_utils.py                    |  25 +-
 unit_testing/cli/test_cli_sct_label_vertebrae.py                |  62 ++-
 unit_testing/cli/test_cli_sct_maths.py                          |  32 +-
 unit_testing/cli/test_cli_sct_merge_images.py                   |  18 +-
 unit_testing/cli/test_cli_sct_process_segmentation.py           |  16 +-
 unit_testing/cli/test_cli_sct_propseg.py                        |  40 +-
 unit_testing/cli/test_cli_sct_qc.py                             |  17 +-
 unit_testing/cli/test_cli_sct_register_multimodal.py            |  49 ++-
 unit_testing/cli/test_cli_sct_register_to_template.py           |  63 ++-
 unit_testing/cli/test_cli_sct_resample.py                       |  27 +-
 unit_testing/cli/test_cli_sct_smooth_spinalcord.py              |  15 +-
 unit_testing/cli/test_cli_sct_straighten_spinalcord.py          |  16 +-
 unit_testing/cli/test_cli_sct_warp_template.py                  |  17 +-
 167 files changed, 2205 insertions(+), 3524 deletions(-)
 create mode 100644 documentation/source/overview/concepts/inspecting-results-qc-fsleyes.rst
 delete mode 100644 documentation/source/overview/concepts/quality-control.rst
 create mode 100644 documentation/source/overview/concepts/warping-fields.rst
 delete mode 100644 documentation/source/tutorials/courses.rst
 delete mode 100644 documentation/source/tutorials/pages/spinalcord_segmentation.rst
 delete mode 100644 documentation/source/tutorials/tutorials.rst
 delete mode 100644 documentation/source/tutorials/video-tutorials.rst
 create mode 100644 documentation/source/user_section/tutorials.rst
 create mode 100644 documentation/source/user_section/tutorials/mtr-computation.rst
 create mode 100644 documentation/source/user_section/tutorials/mtr-computation/before-starting.rst
 create mode 100644 documentation/source/user_section/tutorials/mtr-computation/computing-mtr.rst
 create mode 100644 documentation/source/user_section/tutorials/mtr-computation/coregistering-mt0-mt1.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts/applying-the-warping-fields.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts/before-starting.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts/creating-a-mask.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts/registration-1-reusing-warping-fields.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts/registration-2-direct-registration.rst
 create mode 100644 documentation/source/user_section/tutorials/registering-additional-contrasts/spinalcord-segmentation.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/angle-ap-rl.csv
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/before-starting.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/csa-averaged.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/csa-perlevel.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/csa-perslice.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/csa_c3c4.csv
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/csa_perlevel.csv
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/csa_perslice.csv
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/other-shape-metrics-1.csv
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/other-shape-metrics-2.csv
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/other-shape-metrics.rst
 create mode 100644 documentation/source/user_section/tutorials/shape-metric-computation/verifying-correctness.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/before-starting.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/choosing-an-algorithm.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/contrasts.rst
 rename documentation/source/{tutorials/pages/correcting_sct_propseg.rst => user_section/tutorials/spinalcord-segmentation/fixing-failed-sct_propseg-segmentations.rst} (80%)
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/sct_deepseg_sc-example-t1.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/sct_deepseg_sc.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/sct_propseg-example-t1.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/sct_propseg-example-t2.rst
 create mode 100644 documentation/source/user_section/tutorials/spinalcord-segmentation/sct_propseg.rst
 create mode 100644 documentation/source/user_section/tutorials/template-registration.rst
 create mode 100644 documentation/source/user_section/tutorials/template-registration/applying-the-registration-algorithm.rst
 create mode 100644 documentation/source/user_section/tutorials/template-registration/applying-the-warping-fields.rst
 create mode 100644 documentation/source/user_section/tutorials/template-registration/before-starting.rst
 create mode 100644 documentation/source/user_section/tutorials/template-registration/customizing-registration.rst
 create mode 100644 documentation/source/user_section/tutorials/template-registration/sct_register_to_template.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/applying-the-labeling-algorithm.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/before-starting.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/extracting-specific-labels-for-registration.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/how-many-labels-for-registration.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/labeling-conventions.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/manual-labeling-all-labels.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/manual-labeling-c2c3.rst
 create mode 100644 documentation/source/user_section/tutorials/vertebral-labeling/sct_label_vertebrae.rst
 delete mode 100755 spinalcordtoolbox/scripts/sct_testing.py
 delete mode 100644 testing/test_sct_analyze_lesion.py
 delete mode 100644 testing/test_sct_analyze_texture.py
 delete mode 100644 testing/test_sct_apply_transfo.py
 delete mode 100644 testing/test_sct_compute_ernst_angle.py
 delete mode 100644 testing/test_sct_compute_hausdorff_distance.py
 delete mode 100644 testing/test_sct_compute_mscc.py
 delete mode 100644 testing/test_sct_compute_mtr.py
 delete mode 100644 testing/test_sct_compute_snr.py
 delete mode 100644 testing/test_sct_concat_transfo.py
 delete mode 100644 testing/test_sct_convert.py
 delete mode 100644 testing/test_sct_create_mask.py
 delete mode 100644 testing/test_sct_crop_image.py
 delete mode 100644 testing/test_sct_deepseg_gm.py
 delete mode 100644 testing/test_sct_deepseg_lesion.py
 delete mode 100755 testing/test_sct_deepseg_sc.py
 delete mode 100644 testing/test_sct_denoising_onlm.py
 delete mode 100644 testing/test_sct_detect_pmj.py
 delete mode 100644 testing/test_sct_dice_coefficient.py
 delete mode 100644 testing/test_sct_dmri_compute_bvalue.py
 delete mode 100644 testing/test_sct_dmri_compute_dti.py
 delete mode 100644 testing/test_sct_dmri_concat_b0_and_dwi.py
 delete mode 100644 testing/test_sct_dmri_concat_bvals.py
 delete mode 100644 testing/test_sct_dmri_concat_bvecs.py
 delete mode 100755 testing/test_sct_dmri_moco.py
 delete mode 100755 testing/test_sct_dmri_separate_b0_and_dwi.py
 delete mode 100644 testing/test_sct_dmri_transpose_bvecs.py
 delete mode 100755 testing/test_sct_extract_metric.py
 delete mode 100644 testing/test_sct_flatten_sagittal.py
 delete mode 100644 testing/test_sct_fmri_compute_tsnr.py
 delete mode 100644 testing/test_sct_fmri_moco.py
 delete mode 100755 testing/test_sct_get_centerline.py
 delete mode 100644 testing/test_sct_image.py
 delete mode 100644 testing/test_sct_label_utils.py
 delete mode 100644 testing/test_sct_label_vertebrae.py
 delete mode 100644 testing/test_sct_maths.py
 delete mode 100644 testing/test_sct_merge_images.py
 delete mode 100755 testing/test_sct_process_segmentation.py
 delete mode 100755 testing/test_sct_propseg.py
 delete mode 100755 testing/test_sct_qc.py
 delete mode 100755 testing/test_sct_register_multimodal.py
 delete mode 100755 testing/test_sct_register_to_template.py
 delete mode 100644 testing/test_sct_resample.py
 delete mode 100755 testing/test_sct_smooth_spinalcord.py
 delete mode 100755 testing/test_sct_straighten_spinalcord.py
 delete mode 100755 testing/test_sct_warp_template.py
 create mode 100644 unit_testing/cli/test_cli_sct_denoising_onlm.py
```

</details>

Is it possible that you modified the mode of these files on your end?

**Comment by jcohenadad** [comment]
Also, I tested your code and I'm getting a TypeError:

<details><summary>Terminal output</summary>

```console
julien-macbook:~/temp/20210712_gmchallenge/data_processed/9418 $  sct_compute_snr -i data_concat.nii.gz -method mult -m data1_crop_wmseg_erode.nii.gz -o snr_mult.txt

--
Spinal Cord Toolbox (git-santoshdvc-add-text-output-dfc9454c64ca2acb7416e6ddfdfd0f5ff8bd51dc)

sct_compute_snr -i data_concat.nii.gz -method mult -m data1_crop_wmseg_erode.nii.gz -o snr_mult.txt
--

File data_concat_SNR-mult.nii.gz already exists. Will overwrite it.
File data_concat_mask-STD-nonzeromult.nii.gz already exists. Will overwrite it.

SNR_mult = 20.003156441135573

Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_compute_snr.py", line 213, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_compute_snr.py", line 206, in main
    f.write(snr_roi)
TypeError: write() argument must be str, not numpy.float64
```

</details>

**Comment by santoshdvc** [comment]
About the state of other files, I have not changed them. But let me check if there is some error. And I am fixing the type error soon.

**Comment by santoshdvc** [comment]
I have made another pull request draft, and this time started freshly. Please verify them.

**Comment by joshuacwnewton** [comment]
> When pulling your branch I noticed that the mode of many files changed (and Github does not show it):

@jcohenadad: I think that as long the relevant files don't have their mode changed (in this case, `sct_compute_snr`), this is OK on our end.

(Also, as a quick aside, I would recommend following [this approach](https://stackoverflow.com/a/9153737/7584115) rather than creating a branch then pulling. In this case, it would look something like this:)

```bash
git remote add santoshdvc git@github.com:santoshdvc/spinalcordtoolbox.git
git fetch santoshdvc
# If you want to temporarily check out the fork's branch in a detached HEAD state:
git checkout santoshdvc/add-text-output
# If you want to create a new local branch that tracks the fork's branch:
git checkout -b add-text-output santoshdvc/add-text-output
```

> I have made another pull request draft, and this time started freshly. Please verify them.

@santoshdvc: From SCT's perspective, #3454 and #3455 are basically identical, I think. So, I'm going to close this PR so we can focus on #3455.

(Thanks again for opening this PR!)

**Comment by jcohenadad** [comment]
> Also, just as a quick aside, I would recommend following [this approach](https://stackoverflow.com/a/9153737/7584115) rather than creating a branch then pulling. In this case, it would look something like this:
> 
> ```shell
> git remote add santoshdvc git@github.com:santoshdvc/spinalcordtoolbox.git
> git fetch santoshdvc
> # If you want to temporarily check out the fork's branch in a detached HEAD state:
> git checkout santoshdvc/add-text-output
> # If you want to create a new local branch that tracks the fork's branch:
> git checkout -b add-text-output santoshdvc/add-text-output
> ```

Thank you @joshuacwnewton. I always forget about this. I've now added it in our [internal doc](https://app.gitbook.com/@neuropoly/s/neuropoly-lab/software-development/git#checkout-branch-from-fork), hopefully it will help me not forget...

**Comment by jcohenadad** [comment]
> > Also, just as a quick aside, I would recommend following [this approach](https://stackoverflow.com/a/9153737/7584115) rather than creating a branch then pulling. In this case, it would look something like this:
> > ```shell
> > git remote add santoshdvc git@github.com:santoshdvc/spinalcordtoolbox.git
> > git fetch santoshdvc
> > # If you want to temporarily check out the fork's branch in a detached HEAD state:
> > git checkout santoshdvc/add-text-output
> > # If you want to create a new local branch that tracks the fork's branch:
> > git checkout -b add-text-output santoshdvc/add-text-output
> > ```
> 
> Thank you @joshuacwnewton. I always forget about this. I've now added it in our [internal doc](https://app.gitbook.com/@neuropoly/s/neuropoly-lab/software-development/git#checkout-branch-from-fork), hopefully it will help me not forget...

@joshuacwnewton I did as you suggested and got this:
~~~
julien-macbook:~/code/sct $ git remote add santoshdvc git@github.santoshdvc/spinalcordtoolbox.git
julien-macbook:~/code/sct $ git fetch santoshdvc
fatal: 'git@github.santoshdvc/spinalcordtoolbox.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~~~
We might want to update our [internal doc](https://intranet.neuro.polymtl.ca/software-development/git#checkout-branch-from-fork) once we find the correct syntax

**Comment by joshuacwnewton** [comment]
There's a small typo in the command you used, @jcohenadad:

```bash
# from the original comment
git remote add santoshdvc git@github.com:santoshdvc/spinalcordtoolbox.git

# command with typo
git remote add santoshdvc git@github.santoshdvc/spinalcordtoolbox.git
```

**Comment by jcohenadad** [comment]
sorry about that 🤦

**Comment by jcohenadad** [comment]
issue fixed in our doc

**Pull request closed without merging**
