### PR TITLE
Rescale the affine matrix of an image to accommodate smaller/bigger cord sizes

### LINKED ISSUE #2539: Make it possible to rescale the affine matrix of an image to accommodate smaller/bigger cord sizes
A feature which is currently implemented in `sct_propseg.func_rescale_header()` temporarily changes the matrix size of an image to have propseg work with small/big spinal cords. 

It would be nice to have this feature available for broader use. It could for example be an additional method in `sct_resample -header`.

### PR DESCRIPTION
**Pull request by PaulBautin**
### Description
A feature which is currently implemented in sct_propseg.func_rescale_header() temporarily changes the matrix size of an image to have propseg work with small/big spinal cords.

This PR introduces a new function "rescale_affine" in spinalcordtoolbox/resamplig that allows  the rescaling of the affine matrix of an image to accommodate smaller/bigger cord sizes.

### Usage example:
```
sct_resample -i IMAGE -header-rescale 1 -f 2 -o IMAGE_2xDown
sct_ANYPROCESS -i IMAGE_2xDown -o IMAGE_2xDownProcessed
sct_resample -i IMAGE_2xDownProcessed -header-rescale 1 -f 0.5 -o IMAGE_Processed
```

### Steps to reproduce: (3D image)
[sub-amu01_T1w.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6599425/sub-amu01_T1w.zip)
with code:
`sct_resample -i sub-amu01_T1w.nii.gz -header-rescale 1 -f 2`
output:
[sub-amu01_T1w_ar.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6599456/sub-amu01_T1w_ar.zip)

### Steps to reproduce: (4D image)
[fmri.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6599474/fmri.zip)
with code:
`sct_resample -i fmri.nii.gz -header-rescale 1 -f 2`
output:
[fmri_ar.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6599485/fmri_ar.zip)

Fixes #2539

### CODE REVIEW

**Review by joshuacwnewton — CHANGES_REQUESTED** [review]
Thanks so much for taking the initiative on this! :tada: :smile: 

A couple of comments:

* There's quite a lot of duplication between the new function, `rescale_affine`, and the existing function `resample_nib`. Instead of copying and pasting, what do you think about refactoring the duplicated parts into smaller functions, so that we can reuse the same code between the two functions?
* Now might be a good time to also address #3409, since I think that problem also affects your contribution. (Especially if you choose to refactor `resample_nib` -- we'd already be making significant modifications to this section of the code.)
* There are some linting issues that should be addressed. (If you look in the "Files" view of this PR, you can see some in-code annotations.)
* In the future, could you please keep the pull request template? Thanks much! :slightly_smiling_face:

**Comment by PaulBautin** [comment]
Thanks for the review @joshuacwnewton! 
i agree on the duplication of code between `rescale_affine` and `resample_nib` , i will try to refactor `resample_nib` and address issue #3409 in next commit.

**Comment by joshuacwnewton** [comment]
So, the work in this PR is useful and appreciated, but the one big problem is that... because this is a refactor, GitHub is poorly displaying the total diff for the combined changes. (The "Files Changed" tab is basically unintelligible right now.)

I think the only way for the changes in this PR to become readable would be to break the existing commits down into more atomic commits. That way, it's easier to understand:

* Which parts are refactoring (breaking the existing `resample_nib` into smaller parts)
* Which parts are new (adding an additional `rescale_affine` function)

**Comment by joshuacwnewton** [comment]
I'm currently trying to resolve the conflicts in this branch, and I've realized that the conflicts are from:

* https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3553

So, to be transparent here, as part of the rebase, I'm porting over the fix from https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/e84dfb138573737eba7ca2b0fc12796fb0e07186 into this PR.

**Pull request closed without merging**
