### PR TITLE
Fix bug in Read the Docs

### PR DESCRIPTION
**Pull request by ahill187**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
The variables updated in `custom.css` were being ignored and the default Furo variables were still being used (most noticeably, causing the sidebar to be illegible). This PR used the `light_css_variables` and `dark_css_variables` parameters in `conf.py` to amend it. It looks good on the PR build, but it looked fine in PR #3355 as well and then built differently in the public page, so we may have to merge to verify that it is fixed 😅 

## Linked issues
https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3487

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]
~looking good on my end~  oops! nope: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3489#issuecomment-889868836

**Review by sandrinebedard — APPROVED** [review]
the TOC looks good now! thanks 😊

I was wondering, I checked the dark mode and when I scroll down, I get this:

image

can anyone reproduce?

**Comment by jcohenadad** [comment]
> can anyone reproduce?

yup! i can. Thank you for checking it better than me @sandrinebedard 😅

**Comment by ahill187** [comment]
I can intermittently reproduce the scroll bar, but not the blank boxes? @jcohenadad did you get the blank boxes too?

**Comment by ahill187** [comment]
> the TOC looks good now! thanks 😊
> 
> I was wondering, I checked the dark mode and when I scroll down, I get this:
> 
> image
> 
> can anyone reproduce?

The scrollbar in the sidebar should be fixed, but I can't seem to reproduce the blank boxes? What browser are you on?

**Comment by sandrinebedard** [comment]
> What browser are you on?

I was using chrome!

**Comment by ahill187** [comment]
It looks like there was an update to Furo on July 28, that might be causing some issues...I've downgraded to an earlier version, and pinned Sphinx at 4.1.2 (there is an issue in version 3 of Sphinx that results in the conf.py html variables being ignored). Fingers crossed, I think it works now 🤞

**Comment by ahill187** [comment]
> > What browser are you on?
> 
> I was using chrome!

Hmmm me too! Do you have any idea where the boxes are from?

**Comment by jcohenadad** [comment]
Looking good now on my end 😊

**Comment by sandrinebedard** [comment]
Looks good now! I don’t see the white boxes anymore!!!
Must be linked to the update, thanks for fixing this!

> Do you have any idea where the boxes are from?

 It really  looked like the background of the text was also white, and since the text was white too, I could still see the links that were on the page!

**Comment by ahill187** [comment]
> Looks good now! I don’t see the white boxes anymore!!!
> Must be linked to the update, thanks for fixing this!
> 
> > Do you have any idea where the boxes are from?
> 
> It really looked like the background of the text was also white, and since the text was white too, I could still see the links that were on the page!

No problem! Yes must have been related 😃

**Pull request merged**
