### PR TITLE
Fix FSLeyes script to make it compatible with both FSLeyes v0.34 and v1.0

### LINKED ISSUE #3426: FSLeyes integration script is not compatible with FSLeyes v1.0
### Description

Trying to load `sct_plugin.py` using "Run script" results in the following error dialog:

Screenshot from 2021-06-18 12-35-44

The full traceback is:

```python
 WARNING         runscript.py  107: __doAction      - Script (/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py) could not be executed: 'FSLeyesFrame' object has no attribute 'getAuiManager'
Traceback (most recent call last):
  File "/home/joshua/miniconda/envs/fsleyes-1.0.11-test/lib/python3.9/site-packages/fsleyes/actions/runscript.py", line 101, in __doAction
    runScript(self.__frame,
  File "/home/joshua/miniconda/envs/fsleyes-1.0.11-test/lib/python3.9/site-packages/fsleyes/actions/runscript.py", line 169, in runScript
    exec(code, _globals)
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 36, in <module>
    aui_manager = frame.getAuiManager() # from FSLeyes context
AttributeError: 'FSLeyesFrame' object has no attribute 'getAuiManager'
```

### Steps to Reproduce

Note: If you installed FSLeyes via FSL, and you have FSL v6.0.4 installed (the most recent version at time of writing), you will have gotten FSLeyes v0.34.2. And, upgrading inside the FSL install is not straightforward. 

So, to reproduce, the easiest way is to install FSLeyes v1.0 directly. I simply created a new conda env and installed it as follows:

```
conda create --name fsleyes-1.0.11-test
conda activate fsleyes-1.0.11-test
conda install -c conda-forge fsleyes==1.0.11
```

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [X] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [X] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

This PR fixes an assortment of bugs with SCT's FSLeyes integration script. I have tried to manually test where I could, but further testing from a reviewer would be greatly appreciated. :slightly_smiling_face: 

### Future work

* I plan to update the internal dev docs so that we have a procedure for manual QA (in lieu of automated testing). The idea would be that we could follow the steps before each stable release, just to confirm that the plugin is in working condition.
* Now may also be a good time to rename the script (#3419), however as @jcohenadad notes in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3419#issuecomment-861512598, we would have to do something about the video tutorial. So, I have left this for now.

## Linked issues

Fixes #3426.

### CODE REVIEW

**Comment by jcohenadad** [comment]
Currently testing this PR and got the following message while testing `sct_propseg`:
Screen Shot 2021-06-21 at 9 21 38 AM

my config:
~~~
fsleyes/FSLeyes version 1.0.3
~~~

<details><summary>sct_check_dependencies</summary>

```console
julien-macbook:~/code/sct $ sct_check_dependencies 

--
Spinal Cord Toolbox (git-jn/3426-update-sct_plugin.py-fsleyes-v1.0-28b2aade5df9a28846d64d4440ca7909a0d914b5)

sct_check_dependencies 
--

SCT info:
- version: git-jn/3426-update-sct_plugin.py-fsleyes-v1.0-28b2aade5df9a28846d64d4440ca7909a0d914b5
- path: /Users/julien/code/sct
OS: osx (Darwin-19.6.0-x86_64-i386-64bit)
CPU cores: Available: 16, Used by ITK functions: 16
RAM: Total: 16384MB, Used: 9201MB, Available: 7178MB
Check Python executable.............................[OK]
  Using bundled python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] at /Users/julien/code/sct/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.4.1)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if ivadomed is installed......................[OK] (2.7.4)
Check if matplotlib is installed....................[OK] (3.3.4)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.19.5)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.1.5)
Check if psutil is installed........................[OK] (5.8.0)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.2.4)
Check if pytest-cov is installed....................[OK] (2.12.0)
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.25.1)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.24.2)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0) is installed.................[OK] (1.5.0)
Check if torchvision (0.6.0) is installed...........[OK] (0.6.0)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.60.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.4)
Check if pytest_console_scripts is installed........[OK]
Check if wquantiles is installed....................[OK] (0.4)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened with matplotlib.......[OK] (Using GUI backend: 'MacOSX')
Check if figure can be opened with PyQt.............[OK]

```

</details>

**Comment by jcohenadad** [comment]
Running into the same error after reinstalling SCT. 

<details><summary>Terminal output</summary>

```console
julien-macbook:~/code/sct $ /Users/julien/miniconda3/lib/python3.7/site-packages/dicom/__init__.py:53: UserWarning: 
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org 
for more information.

  warnings.warn(msg)
/Users/julien/miniconda3/lib/python3.7/site-packages/fsleyes/colourmaps.py:570: UserWarning: Trying to register the cmap 'pink' which already exists.
  mplcm.register_cmap(key, cmap, override_builtin=True)
/Users/julien/miniconda3/lib/python3.7/site-packages/fsleyes/colourmaps.py:570: UserWarning: Trying to register the cmap 'hot' which already exists.
  mplcm.register_cmap(key, cmap, override_builtin=True)
/Users/julien/miniconda3/lib/python3.7/site-packages/fsleyes/colourmaps.py:570: UserWarning: Trying to register the cmap 'cool' which already exists.
  mplcm.register_cmap(key, cmap, override_builtin=True)
/Users/julien/miniconda3/lib/python3.7/site-packages/fsleyes/colourmaps.py:570: UserWarning: Trying to register the cmap 'copper' which already exists.
  mplcm.register_cmap(key, cmap, override_builtin=True)
/Users/julien/miniconda3/lib/python3.7/site-packages/fsleyes/colourmaps.py:570: UserWarning: Trying to register the cmap 'hsv' which already exists.
  mplcm.register_cmap(key, cmap, override_builtin=True)
Fetched file name: /Users/julien/sct_testing_data/t1/t1w.nii.gz
Traceback (most recent call last):
  File "/Users/julien/code/sct/contrib/fsl_integration/sct_plugin.py", line 439, in on_button_run
    image = Image(fname_out)  # <class 'fsl.data.image.Image'>
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/fsl/data/image.py", line 1093, in __init__
    image      = op.abspath(addExt(image))
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/fsl/data/image.py", line 1611, in addExt
    raise e
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/fsl/data/image.py", line 1603, in addExt
    unambiguous=unambiguous)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/fsl/utils/path.py", line 199, in addExt
    'with prefix "{}"'.format(prefix))
fsl.utils.path.PathError: Could not find a supported file with prefix "/Users/julien/sct_testing_data/t1/t1w_seg.nii.gz"
```

</details>

**Comment by joshuacwnewton** [comment]
> Running into the same error after reinstalling SCT.

My suspicion is that this is more to do with the FSLeyes installation (and its dependencies), specifically because of this error:

```
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
```

When I created a new conda environment for 1.0.11, I ended up with a Python 3.9 environment and the following packages:

<details>
<summary> Output of conda list </summary>
```
# packages in environment at /home/joshua/miniconda/envs/fsleyes-1.0.11-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
argon2-cffi               20.1.0           py39h3811e60_2    conda-forge
async_generator           1.10                       py_0    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dcm2niix                  1.0.20210317         h4bd325d_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docutils                  0.17.1           py39hf3d152e_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
file-tree                 0.3.5              pyhd8ed1ab_0    conda-forge
file-tree-fsl             0.1.5              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
fsleyes                   1.0.11           py39hf3d152e_0    conda-forge
fsleyes-props             1.7.3              pyhd8ed1ab_0    conda-forge
fsleyes-widgets           0.12.1             pyhd8ed1ab_0    conda-forge
fslpy                     3.6.1              pyh8a188c0_0    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.21.0               hf68c758_0  
glib                      2.68.3               h9c3ff4c_0    conda-forge
glib-tools                2.68.3               h9c3ff4c_0    conda-forge
graphite2                 1.3.14               h23475e2_0  
gst-plugins-base          1.18.4               hf529b03_2    conda-forge
gstreamer                 1.18.4               h76c114f_2    conda-forge
gtk2                      2.24.33              h539f30e_1    conda-forge
h5py                      3.2.1           nompi_py39h98ba4bc_100    conda-forge
harfbuzz                  2.8.1                h83ec7ef_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        4.5.0            py39hf3d152e_0    conda-forge
indexed_gzip              1.6.0            py39h4a16fb3_0    conda-forge
ipykernel                 5.5.5            py39hef51801_0    conda-forge
ipython                   7.24.1           py39hef51801_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.0           py39hf3d152e_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kiwisolver                1.3.1            py39h1a9c180_1    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20210216         h27cfd23_1  
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libglib                   2.68.3               h3e27bee_0    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_3    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h72842e0_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                2.0.1            py39h3811e60_0    conda-forge
matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mesalib                   18.3.1               h590aaf7_0    conda-forge
mistune                   0.8.4           py39h3811e60_1003    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py39hf3d152e_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
nibabel                   3.2.1              pyhd8ed1ab_0    conda-forge
notebook                  6.4.0              pyha770c72_0    conda-forge
numpy                     1.20.3           py39hdbf815f_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.4            py39hde0f152_0    conda-forge
pandoc                    2.14.0.2             h7f98852_0    conda-forge
pandocfilters             1.4.3            py39h06a4308_1  
pango                     1.48.5               hb8ff022_0    conda-forge
parse                     1.19.0             pyh44b312d_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pathlib2                  2.3.5            py39hf3d152e_3    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.2.0            py39hf95b381_1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydicom                   2.1.2              pyhd3deb0d_0    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.5                      py_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyrsistent                0.17.3           py39h3811e60_2    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.5                h12debd9_4  
python-dateutil           2.8.1                      py_0    conda-forge
python-utils              2.5.6              pyh44b312d_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyzmq                     22.1.0           py39h37b5a0c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rtree                     0.9.7            py39hb102c33_1    conda-forge
scipy                     1.6.3            py39hee8e79c_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                52.0.0           py39h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.0.2              pyh6c4a22f_1    conda-forge
sphinx_rtd_theme          0.5.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
terminado                 0.10.1           py39hf3d152e_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py39h3811e60_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
trimesh                   3.9.20             pyh6c4a22f_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wxnatpy                   0.3.2                      py_0    conda-forge
wxpython                  4.1.1            py39h09f47c6_1    conda-forge
xarray                    0.18.2             pyhd8ed1ab_0    conda-forge
xnat                      0.3.26             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```
</details>

In that list of packages, I have a much newer `pydicom` package, which was mentioned by the error message:

```
pydicom                   2.1.2              pyhd3deb0d_0    conda-forge
```

**Comment by jcohenadad** [comment]
I've also tried running FSLeyes installed by shimming-toolbox, which is at version: 0.34.2, and I observe the same error. So it is likely that the error I am observing is unrelated to this PR and I should probably open a new issue specific to this error.

**Comment by joshuacwnewton** [comment]
Oops, sorry. I didn't realize there were 2 error messages in your pasted output. I can fix the second one (Image not found).

**Comment by joshuacwnewton** [comment]
Hmm... I was unable to reproduce the File not found error with my current FSLeyes v1.0 conda environment:

Screenshot from 2021-06-21 10-29-41

It also worked for FSLeyes v0.34.2 (which had been installed via FSL). (The screenshots are basically identical, though.)

For your FSLeyes v1.0.3 conda environment, could you share the output of `conda list`?

**Comment by jcohenadad** [comment]
> I would try starting with a fresh conda environment and installing FSLeyes via

Trying it now

**Comment by jcohenadad** [comment]
hum... maybe my conda is suspicious...

~~~
julien-macbook:~ $ conda env create -n fsleyes

SpecNotFound: Invalid name, try the format: user/package

julien-macbook:~ $ conda env create

EnvironmentFileNotFound: '/Users/julien/environment.yml' file not found
~~~

**Comment by jcohenadad** [comment]
maybe I should just reinstall miniconda...?
~~~
julien-macbook:~ $ conda info

     active environment : None
            shell level : 0
       user config file : /Users/julien/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.7.10.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/julien/miniconda3  (writable)
      conda av data dir : /Users/julien/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/julien/miniconda3/pkgs
                          /Users/julien/.conda/pkgs
       envs directories : /Users/julien/miniconda3/envs
                          /Users/julien/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.10 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False
~~~

**Comment by joshuacwnewton** [comment]
> hum... maybe my conda is suspicious...
> 
> ```
> julien-macbook:~ $ conda env create -n fsleyes
> 
> SpecNotFound: Invalid name, try the format: user/package
> 
> julien-macbook:~ $ conda env create
> 
> EnvironmentFileNotFound: '/Users/julien/environment.yml' file not found
> ```

I used `conda create -n` rather than `conda env create -n`. :slightly_smiling_face:

**Comment by jcohenadad** [comment]
At this point, should I just reinstall miniconda?

**Comment by joshuacwnewton** [comment]
Ah! There was at least some progress: Creating a fresh conda environment removed the "pydicom" warning that was present in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3427#issuecomment-865073301. So, there were 3 issues, and now we're left with 2...

> ```
> Could not find platform independent libraries <prefix>
> Could not find platform dependent libraries <exec_prefix>
> ```

Looking into this now.... e.g. [this SO answer](https://stackoverflow.com/a/24044339)

> Normally, when you receive the error message `Could not find platform independent libraries <prefix>`, the string `<prefix>` would be replaced with the actual value of prefix. However, if prefix has an empty value, then you get the rather cryptic messages posted in the question.

**Comment by jcohenadad** [comment]
Even weirder: I reinstalled miniconda, and fsleyes, but I am still getting the same behaviour.

**Comment by jcohenadad** [comment]
I also renamed `~./fsleyes` to `~./fsleyes_old`, but again got the same errors.

**Comment by joshuacwnewton** [comment]
Could you try running these commands after activating the environment you created for FSLeyes v1.0?

```bash
conda info
python -m site
```

**Comment by jcohenadad** [comment]
julien-macbook:~ $ conda info

     active environment : base
    active env location : /Users/julien/opt/miniconda3
            shell level : 1
       user config file : /Users/julien/.condarc
 populated config files : /Users/julien/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/julien/opt/miniconda3  (writable)
      conda av data dir : /Users/julien/opt/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/julien/opt/miniconda3/pkgs
                          /Users/julien/.conda/pkgs
       envs directories : /Users/julien/opt/miniconda3/envs
                          /Users/julien/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.0 CPython/3.9.1 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False

julien-macbook:~ $ python -m site
sys.path = [
    '/Users/julien',
    '/Users/julien/opt/miniconda3/lib/python39.zip',
    '/Users/julien/opt/miniconda3/lib/python3.9',
    '/Users/julien/opt/miniconda3/lib/python3.9/lib-dynload',
    '/Users/julien/opt/miniconda3/lib/python3.9/site-packages',
]
USER_BASE: '/Users/julien/.local' (exists)
USER_SITE: '/Users/julien/.local/lib/python3.9/site-packages' (doesn't exist)
ENABLE_USER_SITE: True

**Comment by joshuacwnewton** [comment]
Hmmm... OK. I think the `conda` environment is fine.

I'm at a bit of a loss right now, but I'll try to reproduce in my macOS VM to see if it's perhaps a platform-specific thing.

**Comment by jcohenadad** [comment]
p.s. the good ol' "reboot" method didn't help either 😅

**Comment by joshuacwnewton** [comment]
Aha! I am able to reproduce on my macOS VM. I will look into this further, then -- no need to continue digging on your end. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
I have a fix! 

I [compared the environment variables](https://www.diffchecker.com/6fY70qJG) between my personal Ubuntu environment (working) and my macOS VM (not working). In that diff, I noticed that [`PYTHONEXECUTABLE`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONEXECUTABLE) was set in the macOS environment.

> **PYTHONEXECUTABLE**
>     If this environment variable is set, sys.argv[0] will be set to its value instead of the value got through the C runtime. Only works on Mac OS X.

For me, it was set to `/Users/joshua/miniconda3/bin/python`. While this is relevant for the FSLeyes context, this is definitely the wrong executable for the SCT context, and so it shouldn't be set when we call the SCT command in `sct_plugin.py`.

Unsetting this variable fixed the problem for me. I'll push a fix in a moment.

**Comment by jcohenadad** [comment]
yay! 24e7f83 fixed the issue 🎉 
@joshuacwnewton you're amazing

**Review by jcohenadad — APPROVED** [review]
tested, it works!

**Pull request merged**
