### PR TITLE
Fix table size and scrolling in the QC report

### PR DESCRIPTION
**Pull request by TommyBoshkovski**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've applied a [release milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestones) (major, minor, patch) in line with [Semantic Versioning guidelines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#convention-for-naming-releases) 
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [SCT's internal developer documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
This PR address the issues with large tables and scrolling in the QC report.
I've changed the height of the table (made it fixed size) and added a function to control the scrolling when the user uses the arrow keys on the keyboard to navigate through it. 

## Linked issues
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/3384

### CODE REVIEW

**Review by joshuacwnewton — COMMENTED** [review]
Thank you so much for doing this! :tada: 

I tested this by taking @sandrinebedard's QC folder from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3384#issuecomment-837447477 and patching in the changes to `qc/_assets/js/main.js` and `qc/index.html`. (I figured it was easier than trying to generate 100+ subjects from scratch on the branch, but maybe there's a better way.) 

Note: Trying to manually edit `index.html` caused my text editor to slow way down due to how we store table entries. To make things easier, here's an edited version with all of the subjects that you can paste into the QC folder: [index.html.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6480173/index.html.zip).

Both issues are fixed for me! :smile: 

This is a bit outside of the scope of the original issue, but some comments:

* How difficult would it be to try and keep the header fixed so that it's always visible even when scrolling? (Something like [this SO discussion](https://stackoverflow.com/questions/21168521/table-fixed-header-and-scrollable-body).)
* I notice that our half-width view doesn't look too great. With the new table height, there's a big white space between the table and the QC images, so the QC images get pushed off the page. (I'm not sure if this is something we care too much about, though.)

<details>
<summary> Screenshots </summary>

Screenshot from 2021-05-14 13-09-07

Screenshot from 2021-05-14 13-09-13

<details>

**Review by sandrinebedard — COMMENTED** [review]
Thank you for fixing this @TommyBoshkovski 😊

I regenerated the large QC on the branch and both issues are fixed for me!

However, I tested out the interactive part and the table always goes back up whenever I click on "F":

https://user-images.githubusercontent.com/71230552/118311367-cf9e2a80-b4bd-11eb-87c1-9914986ea098.mp4

**Review by sandrinebedard — COMMENTED** [review]
I also just noticed that I am not able to write anything in the search bar 🤔

**Comment by TommyBoshkovski** [comment]
@sandrinebedard and @joshuacwnewton thanks for testing it. I've made some changes, so it should be working fine now.

**Comment by sandrinebedard** [comment]
I tested it out and the scrolling and searching work fine! Thanks @TommyBoshkovski 
One thing I noticed, when using the search bar, I am not able to use the interactive feature, can anyone reproduce?

**Comment by jcohenadad** [comment]
> One thing I noticed, when using the search bar, I am not able to use the interactive feature, can anyone reproduce?

Hum, I'm not sure I understand what you mean @sandrinebedard ? The search box works well (see below). 

However, I noticed something quite annoying, which is that when the number of rows is higher than the maximum displaued rows, the table does not scroll down and we loose track of the selected subjects. We need to use manually scroll to find the subject, but it would be much more convenient if the scrolling would follow the selected subject:

https://user-images.githubusercontent.com/2482071/118524602-52b4c000-b70c-11eb-9a37-8c26851169b1.mov

@TommyBoshkovski can you use your magical powers to make this happen?  🙏  😊

**Comment by sandrinebedard** [comment]
> Hum, I'm not sure I understand what you mean @sandrinebedard ? The search box works well (see below).

@jcohenadad the search box works well, but I can't use the interactve QC feature with ✅, ❌, ⚠️(example bellow)

https://user-images.githubusercontent.com/71230552/118526376-2b5ef280-b70e-11eb-9a77-f10fef023a38.mp4

(btw I am clicking on 'F' 😅)

**Comment by sandrinebedard** [comment]
> However, I noticed something quite annoying, which is that when the number of rows is higher than the maximum displaued rows, the table does not scroll down and we loose track of the selected subjects. We need to use manually scroll to find the subject, but it would be much more convenient if the scrolling would follow the selected subject

@jcohenadad I think it is already resolved! 


https://user-images.githubusercontent.com/71230552/118527314-28b0cd00-b70f-11eb-89c5-fd0d36ac5cfb.mp4

**Comment by TommyBoshkovski** [comment]
@jcohenadad  and @sandrinebedard, I've fixed the QC interactivity as well as the table scrolling. Now, The table automatically scrolls so that the highlighted subject is ussually at the top of the table.

**Review by sandrinebedard — COMMENTED** [review]
Hmm, I get stuck here and the table/images are not displayed:

image

**Comment by TommyBoshkovski** [comment]
Thanks for catching this @sandrinebedard! There was a typo in the js, but now it's fixed :)

**Comment by sandrinebedard** [comment]
Thank you @TommyBoshkovski, the QC interactivity works when using the search box! For the scrolling, the highlighted subject is at the top when using the interactivity, but is at the bottom if not. However, the interactivity doesn't work when I order by subject or by function and the scrolling doesn't follow the highlighted subject:


https://user-images.githubusercontent.com/71230552/118823980-72242800-b887-11eb-853d-7376adb0bdb2.mp4

**Comment by sandrinebedard** [comment]
The interactivity works with the sorting! 🎉
However, I am not able to click on the first image or to display it:


https://user-images.githubusercontent.com/71230552/118856014-71e65580-b8a4-11eb-9228-d222181059ed.mp4

**Review by sandrinebedard — APPROVED** [review]
I tested out the latest version and everything looks good on my side!
Thanks @TommyBoshkovski for resolving all these issues 🙏

**Comment by TommyBoshkovski** [comment]
No worries @sandrinebedard! 
@jcohenadad  I don't have permission to merge the branch, so could you please merge after you test it, ofc if it is ok 😃  . If there is still something missing or not working right, please let me know. 😃

**Comment by jcohenadad** [comment]
@TommyBoshkovski It is much better now, thank you so much!  There are just two non-intuitive behaviours that remain:

1) When clicking with the mouse on a particular row, the row moves to the top of the table, which gives the impression that the row was not properly selected (because it "moves away" from the mouse cursor). See here:

https://user-images.githubusercontent.com/2482071/118999331-2e4d2380-b958-11eb-9ceb-7389a040480b.mov

2) Going up with the keyboard arrow, when arriving at the top, it would be nice to _see_ the top of the table (otherwise we are not sure if we arrived at the top). See here:

https://user-images.githubusercontent.com/2482071/118999578-63f20c80-b958-11eb-8af2-8f13c8d8075b.mov

If it is too difficult to solve, don't worry. These are minor issues.

**Comment by TommyBoshkovski** [comment]
@jcohenadad  I think I've addressed your comments. I had to add an additional prototype js function because some of the function I was using is available only on Chrome and Safari but not on Firefox. However, I tested it on Firefox and Chrome and it seems to be working now.

**Comment by jcohenadad** [comment]
Tested 8962289634fba2f257244fc65dce5fb96b5349d0 and it solves the issues raised in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3389#issuecomment-845185840 🎉 

My testing setup:
~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
for i in {0..20}; do sct_qc -i t2.nii.gz -s t2_seg-manual.nii.gz -p sct_deepseg_sc -qc qc-20210529; done
# use another function to test the "search" feature
for i in {0..20}; do sct_qc -i t2.nii.gz -s t2_seg-manual.nii.gz -p sct_propseg -qc qc-20210529; done
~~~

There is a slight different in the rendering of the table at the bottom (the table is "cut"), but this is really not a big deal:
Screen Shot 2021-05-29 at 9 30 47 PM

Thank you _so much_ for helping us with this @TommyBoshkovski 🙏  ❤️

**Review by jcohenadad — APPROVED** [review]
Everything works fine now 😊

**Comment by joshuacwnewton** [comment]
Huzzah! Thanks so much, @TommyBoshkovski. :tada: 

With two approvals, I'm going to merge this now. :slightly_smiling_face:

**Pull request merged**
