### PR TITLE
Fix softseg QC by using only a single transparency value (`alpha=1.0`)

### LINKED ISSUE #4735: QC of sct_deepseg displays "soft" segmentations
## Description

When running the Qc report in `sct_deepseg` function, the segmentation ouput in the QC report is soft, but when rerunning the command with `sct_qc -p sct_deepseg_sc`, the ouput in the QC is binarized. I know it can be useful to have it soft if the flag `-thr 0` is used, but the visual is a bit weird.

I would suggest to binarize also the `sct_deepseg` QC if the flag `-thr 0` is not there? 

### `sct_deepseg` QC
Capture d’écran, le 2024-12-02 à 11 34 47

### `sct_deepseg_sc` QC
Capture d’écran, le 2024-12-02 à 11 35 09

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

Request by @sandrinebedard.

Before: 

image

After: 

image

## Linked issues

Fixes #4735.

### CODE REVIEW

**Review by sandrinebedard — APPROVED** [review]
Thanks for this @joshuacwnewton ! I am curious thta the results looks very different:

This is contrast-agnostic on the T2star of the course material:

Before:
image

After: 

image

So I think with the alpha, we were missing some part of the segmentation, curious!

**Comment by mguaypaq** [comment]
It looks a bit weird that the ALRP labels are "under" the segmentation. But I guess that's because they're drawn on the background image, and not on the foreground image. Not a big deal.

**Comment by sandrinebedard** [comment]
I also noticed that!

**Comment by sandrinebedard** [comment]
and on other images: 
image
 maybe we should fix too

**Comment by joshuacwnewton** [comment]
> So I think with the alpha, we were missing some part of the segmentation, curious!

Maybe there were values very close to 0, making them pretty much transparent?

> and on other images, they are not at the right spot:

Just fixed now in:

- #4736

**Pull request merged**
