### PR TITLE
Better isolate the SCT conda env by using `-p` instead of `-n` during creation

### LINKED ISSUE #3982: `.condarc` `envs_dirs:` breaks `install_sct`
### Description

If an env named `venv_sct` predates running `./install_sct`, the installation will fail.

### Steps to Reproduce

1. Install miniconda from https://github.com/conda-forge/miniforge

    <details>

      ```console
      p115628@joplin:~$ curl -JLO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    100 61.8M  100 61.8M    0     0  21.6M      0  0:00:02  0:00:02 --:--:-- 24.3M
    p115628@joplin:~$ sh ./Miniforge3-Linux-x86_64.sh -b
    PREFIX=/home/GRAMES.POLYMTL.CA/p115628/miniforge3
    Unpacking payload ...
    Extracting python-3.10.6-ha86cf86_0_cpython.tar.bz2
    Extracting _libgcc_mutex-0.1-conda_forge.tar.bz2
    Extracting ca-certificates-2022.9.24-ha878542_0.tar.bz2
    Extracting ld_impl_linux-64-2.39-hc81fddc_0.tar.bz2
    Extracting tzdata-2022f-h191b570_0.tar.bz2
    Extracting libgomp-12.2.0-h65d4601_19.tar.bz2
    Extracting _openmp_mutex-4.5-2_gnu.tar.bz2
    Extracting libgcc-ng-12.2.0-h65d4601_19.tar.bz2
    Extracting bzip2-1.0.8-h7f98852_4.tar.bz2
    Extracting libffi-3.4.2-h7f98852_5.tar.bz2
    Extracting libnsl-2.0.0-h7f98852_0.tar.bz2
    Extracting libuuid-2.32.1-h7f98852_1000.tar.bz2
    Extracting libzlib-1.2.13-h166bdaf_4.tar.bz2
    Extracting ncurses-6.3-h27087fc_1.tar.bz2
    Extracting openssl-3.0.7-h166bdaf_0.tar.bz2
    Extracting xz-5.2.6-h166bdaf_0.tar.bz2
    Extracting yaml-0.2.5-h7f98852_2.tar.bz2
    Extracting libsqlite-3.40.0-h753d276_0.tar.bz2
    Extracting readline-8.1.2-h0f457ee_0.tar.bz2
    Extracting tk-8.6.12-h27826a3_0.tar.bz2
    Extracting certifi-2022.9.24-pyhd8ed1ab_0.tar.bz2
    Extracting charset-normalizer-2.1.1-pyhd8ed1ab_0.tar.bz2
    Extracting colorama-0.4.6-pyhd8ed1ab_0.tar.bz2
    Extracting idna-3.4-pyhd8ed1ab_0.tar.bz2
    Extracting pycparser-2.21-pyhd8ed1ab_0.tar.bz2
    Extracting pysocks-1.7.1-pyha2e5f31_6.tar.bz2
    Extracting python_abi-3.10-2_cp310.tar.bz2
    Extracting setuptools-65.5.1-pyhd8ed1ab_0.tar.bz2
    Extracting toolz-0.12.0-pyhd8ed1ab_0.tar.bz2
    Extracting wheel-0.38.4-pyhd8ed1ab_0.tar.bz2
    Extracting cffi-1.15.1-py310h255011f_2.tar.bz2
    Extracting pip-22.3.1-pyhd8ed1ab_0.tar.bz2
    Extracting pycosat-0.6.4-py310h5764c6d_1.tar.bz2
    Extracting ruamel_yaml-0.15.80-py310h5764c6d_1008.tar.bz2
    Extracting tqdm-4.64.1-pyhd8ed1ab_0.tar.bz2
    Extracting brotlipy-0.7.0-py310h5764c6d_1005.tar.bz2
    Extracting conda-package-handling-1.9.0-py310h5764c6d_1.tar.bz2
    Extracting cryptography-38.0.3-py310h600f1e7_0.tar.bz2
    Extracting pyopenssl-22.1.0-pyhd8ed1ab_0.tar.bz2
    Extracting urllib3-1.26.11-pyhd8ed1ab_0.tar.bz2
    Extracting requests-2.28.1-pyhd8ed1ab_1.tar.bz2
    Extracting conda-22.9.0-py310hff52083_2.tar.bz2

                                               __
              __  ______ ___  ____ _____ ___  / /_  ____ _
             / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
            / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
           / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
          /_/

    conda-forge/linux-64                                        Using cache
    conda-forge/noarch                                          Using cache

    Transaction

      Prefix: /home/GRAMES.POLYMTL.CA/p115628/miniforge3

      Updating specs:

       - python==3.10.6=ha86cf86_0_cpython
       - _libgcc_mutex==0.1=conda_forge
       - ca-certificates==2022.9.24=ha878542_0
       - ld_impl_linux-64==2.39=hc81fddc_0
       - tzdata==2022f=h191b570_0
       - libgomp==12.2.0=h65d4601_19
       - _openmp_mutex==4.5=2_gnu
       - libgcc-ng==12.2.0=h65d4601_19
       - bzip2==1.0.8=h7f98852_4
       - libffi==3.4.2=h7f98852_5
       - libnsl==2.0.0=h7f98852_0
       - libuuid==2.32.1=h7f98852_1000
       - libzlib==1.2.13=h166bdaf_4
       - ncurses==6.3=h27087fc_1
       - openssl==3.0.7=h166bdaf_0
       - xz==5.2.6=h166bdaf_0
       - yaml==0.2.5=h7f98852_2
       - libsqlite==3.40.0=h753d276_0
       - readline==8.1.2=h0f457ee_0
       - tk==8.6.12=h27826a3_0
       - certifi==2022.9.24=pyhd8ed1ab_0
       - charset-normalizer==2.1.1=pyhd8ed1ab_0
       - colorama==0.4.6=pyhd8ed1ab_0
       - idna==3.4=pyhd8ed1ab_0
       - pycparser==2.21=pyhd8ed1ab_0
       - pysocks==1.7.1=pyha2e5f31_6
       - python_abi==3.10=2_cp310
       - setuptools==65.5.1=pyhd8ed1ab_0
       - toolz==0.12.0=pyhd8ed1ab_0
       - wheel==0.38.4=pyhd8ed1ab_0
       - cffi==1.15.1=py310h255011f_2
       - pip==22.3.1=pyhd8ed1ab_0
       - pycosat==0.6.4=py310h5764c6d_1
       - ruamel_yaml==0.15.80=py310h5764c6d_1008
       - tqdm==4.64.1=pyhd8ed1ab_0
       - brotlipy==0.7.0=py310h5764c6d_1005
       - conda-package-handling==1.9.0=py310h5764c6d_1
       - cryptography==38.0.3=py310h600f1e7_0
       - pyopenssl==22.1.0=pyhd8ed1ab_0
       - urllib3==1.26.11=pyhd8ed1ab_0
       - requests==2.28.1=pyhd8ed1ab_1
       - conda==22.9.0=py310hff52083_2


      Package                     Version  Build               Channel                    Size
    ────────────────────────────────────────────────────────────────────────────────────────────
      Install:
    ────────────────────────────────────────────────────────────────────────────────────────────

      + _libgcc_mutex                 0.1  conda_forge         conda-forge/linux-64     Cached
      + _openmp_mutex                 4.5  2_gnu               conda-forge/linux-64     Cached
      + brotlipy                    0.7.0  py310h5764c6d_1005  conda-forge/linux-64     Cached
      + bzip2                       1.0.8  h7f98852_4          conda-forge/linux-64     Cached
      + ca-certificates         2022.9.24  ha878542_0          conda-forge/linux-64     Cached
      + certifi                 2022.9.24  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + cffi                       1.15.1  py310h255011f_2     conda-forge/linux-64     Cached
      + charset-normalizer          2.1.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + colorama                    0.4.6  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + conda                      22.9.0  py310hff52083_2     conda-forge/linux-64     Cached
      + conda-package-handling      1.9.0  py310h5764c6d_1     conda-forge/linux-64     Cached
      + cryptography               38.0.3  py310h600f1e7_0     conda-forge/linux-64     Cached
      + idna                          3.4  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + ld_impl_linux-64             2.39  hc81fddc_0          conda-forge/linux-64     Cached
      + libffi                      3.4.2  h7f98852_5          conda-forge/linux-64     Cached
      + libgcc-ng                  12.2.0  h65d4601_19         conda-forge/linux-64     Cached
      + libgomp                    12.2.0  h65d4601_19         conda-forge/linux-64     Cached
      + libnsl                      2.0.0  h7f98852_0          conda-forge/linux-64     Cached
      + libsqlite                  3.40.0  h753d276_0          conda-forge/linux-64     Cached
      + libuuid                    2.32.1  h7f98852_1000       conda-forge/linux-64     Cached
      + libzlib                    1.2.13  h166bdaf_4          conda-forge/linux-64     Cached
      + ncurses                       6.3  h27087fc_1          conda-forge/linux-64     Cached
      + openssl                     3.0.7  h166bdaf_0          conda-forge/linux-64     Cached
      + pip                        22.3.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + pycosat                     0.6.4  py310h5764c6d_1     conda-forge/linux-64     Cached
      + pycparser                    2.21  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + pyopenssl                  22.1.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + pysocks                     1.7.1  pyha2e5f31_6        conda-forge/noarch       Cached
      + python                     3.10.6  ha86cf86_0_cpython  conda-forge/linux-64     Cached
      + python_abi                   3.10  2_cp310             conda-forge/linux-64     Cached
      + readline                    8.1.2  h0f457ee_0          conda-forge/linux-64     Cached
      + requests                   2.28.1  pyhd8ed1ab_1        conda-forge/noarch       Cached
      + ruamel_yaml               0.15.80  py310h5764c6d_1008  conda-forge/linux-64     Cached
      + setuptools                 65.5.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + tk                         8.6.12  h27826a3_0          conda-forge/linux-64     Cached
      + toolz                      0.12.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + tqdm                       4.64.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + tzdata                      2022f  h191b570_0          conda-forge/noarch       Cached
      + urllib3                   1.26.11  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + wheel                      0.38.4  pyhd8ed1ab_0        conda-forge/noarch       Cached
      + xz                          5.2.6  h166bdaf_0          conda-forge/linux-64     Cached
      + yaml                        0.2.5  h7f98852_2          conda-forge/linux-64     Cached

      Summary:

      Install: 42 packages

      Total download: 0 B

    ────────────────────────────────────────────────────────────────────────────────────────────


    Transaction starting
    Linking _libgcc_mutex-0.1-conda_forge
    Linking ca-certificates-2022.9.24-ha878542_0
    Linking ld_impl_linux-64-2.39-hc81fddc_0
    Linking libgomp-12.2.0-h65d4601_19
    Linking _openmp_mutex-4.5-2_gnu
    Linking libgcc-ng-12.2.0-h65d4601_19
    Linking yaml-0.2.5-h7f98852_2
    Linking xz-5.2.6-h166bdaf_0
    Linking openssl-3.0.7-h166bdaf_0
    Linking ncurses-6.3-h27087fc_1
    Linking libzlib-1.2.13-h166bdaf_4
    Linking libuuid-2.32.1-h7f98852_1000
    Linking libnsl-2.0.0-h7f98852_0
    Linking libffi-3.4.2-h7f98852_5
    Linking bzip2-1.0.8-h7f98852_4
    Linking readline-8.1.2-h0f457ee_0
    Linking tk-8.6.12-h27826a3_0
    Linking libsqlite-3.40.0-h753d276_0
    Linking tzdata-2022f-h191b570_0
    Linking python-3.10.6-ha86cf86_0_cpython
    Linking wheel-0.38.4-pyhd8ed1ab_0
    Linking setuptools-65.5.1-pyhd8ed1ab_0
    Linking pip-22.3.1-pyhd8ed1ab_0
    Linking toolz-0.12.0-pyhd8ed1ab_0
    Linking pysocks-1.7.1-pyha2e5f31_6
    Linking pycparser-2.21-pyhd8ed1ab_0
    Linking idna-3.4-pyhd8ed1ab_0
    Linking colorama-0.4.6-pyhd8ed1ab_0
    Linking charset-normalizer-2.1.1-pyhd8ed1ab_0
    Linking certifi-2022.9.24-pyhd8ed1ab_0
    Linking tqdm-4.64.1-pyhd8ed1ab_0
    Linking python_abi-3.10-2_cp310
    Linking conda-package-handling-1.9.0-py310h5764c6d_1
    Linking ruamel_yaml-0.15.80-py310h5764c6d_1008
    Linking pycosat-0.6.4-py310h5764c6d_1
    Linking cffi-1.15.1-py310h255011f_2
    Linking cryptography-38.0.3-py310h600f1e7_0
    Linking brotlipy-0.7.0-py310h5764c6d_1005
    Linking pyopenssl-22.1.0-pyhd8ed1ab_0
    Linking urllib3-1.26.11-pyhd8ed1ab_0
    Linking requests-2.28.1-pyhd8ed1ab_1
    Linking conda-22.9.0-py310hff52083_2
    Transaction finished
    installation finished.
    ```

    </details>

2. Set up this [condarc](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-env-directories)

    ```
    p115628@joplin:~/spinalcordtoolbox$ cat ~/.condarc 
    envs_dirs:
      - ~/miniforge3/envs/
    ```

3. Download and run `install_sct`.

**Expected behavior:** SCT installs and works.

We're using `conda`, in fact installing an entirely separate copy of conda regardless of whether the user has it on their system already, because we are very concerned about controlling exactly what is in the environment and where.

**Actual behavior:**

Install fails at

> ./install_sct: ligne 605: spinalcordtoolbox/python/envs/venv_sct/pyvenv.cfg: Aucun fichier ou dossier de ce type

<details>

```
p115628@joplin:~/spinalcordtoolbox$ ./install_sct -y
 non-interactive mode


*******************************
* Welcome to SCT installation *
*******************************



Checking OS type and version...

Linux joplin.neuro.polymtl.ca 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Checking requirements...


OK!


SCT version ......... dev
Installation type ... in-place
Operating system .... linux (unknown)
Shell config ........ /home/GRAMES.POLYMTL.CA/p115628/.bashrc

--> Crash reports will not be sent.


SCT will be installed here: [/home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox]


Skipping copy of source files (source and destination folders are the same)


Removing sct and isct softlink from /home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/bin


rm -rf /home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/python


mkdir -p /home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/python


Downloading Miniconda...


wget -nv -O /tmp/tmp.7eisickG8Y/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

2022-12-19 19:22:58 URL:https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh [76607678/76607678] -> "/tmp/tmp.7eisickG8Y/miniconda.sh" [1]

Installing Miniconda...


bash /tmp/tmp.7eisickG8Y/miniconda.sh -p /home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/python -b -f

PREFIX=/home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/python
Unpacking payload ...
Collecting package metadata (current_repodata.json): ...working... done                                       
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/python

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - _openmp_mutex==4.5=1_gnu
    - brotlipy==0.7.0=py39h27cfd23_1003
    - ca-certificates==2022.3.29=h06a4308_1
    - certifi==2021.10.8=py39h06a4308_2
    - cffi==1.15.0=py39hd667e15_1
    - charset-normalizer==2.0.4=pyhd3eb1b0_0
    - colorama==0.4.4=pyhd3eb1b0_0
    - conda-content-trust==0.1.1=pyhd3eb1b0_0
    - conda-package-handling==1.8.1=py39h7f8727e_0
    - conda==4.12.0=py39h06a4308_0
    - cryptography==36.0.0=py39h9ce1e76_0
    - idna==3.3=pyhd3eb1b0_0
    - ld_impl_linux-64==2.35.1=h7274673_9
    - libffi==3.3=he6710b0_2
    - libgcc-ng==9.3.0=h5101ec6_17
    - libgomp==9.3.0=h5101ec6_17
    - libstdcxx-ng==9.3.0=hd4cf53a_17
    - ncurses==6.3=h7f8727e_2
    - openssl==1.1.1n=h7f8727e_0
    - pip==21.2.4=py39h06a4308_0
    - pycosat==0.6.3=py39h27cfd23_0
    - pycparser==2.21=pyhd3eb1b0_0
    - pyopenssl==22.0.0=pyhd3eb1b0_0
    - pysocks==1.7.1=py39h06a4308_0
    - python==3.9.12=h12debd9_0
    - readline==8.1.2=h7f8727e_1
    - requests==2.27.1=pyhd3eb1b0_0
    - ruamel_yaml==0.15.100=py39h27cfd23_0
    - setuptools==61.2.0=py39h06a4308_0
    - six==1.16.0=pyhd3eb1b0_1
    - sqlite==3.38.2=hc218d9a_0
    - tk==8.6.11=h1ccaba5_0
    - tqdm==4.63.0=pyhd3eb1b0_0
    - tzdata==2022a=hda174b7_0
    - urllib3==1.26.8=pyhd3eb1b0_0
    - wheel==0.37.1=pyhd3eb1b0_0
    - xz==5.2.5=h7b6447c_0
    - yaml==0.2.5=h7b6447c_0
    - zlib==1.2.12=h7f8727e_1


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  brotlipy           pkgs/main/linux-64::brotlipy-0.7.0-py39h27cfd23_1003
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.3.29-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.10.8-py39h06a4308_2
  cffi               pkgs/main/linux-64::cffi-1.15.0-py39hd667e15_1
  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0
  colorama           pkgs/main/noarch::colorama-0.4.4-pyhd3eb1b0_0
  conda              pkgs/main/linux-64::conda-4.12.0-py39h06a4308_0
  conda-content-tru~ pkgs/main/noarch::conda-content-trust-0.1.1-pyhd3eb1b0_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.8.1-py39h7f8727e_0
  cryptography       pkgs/main/linux-64::cryptography-36.0.0-py39h9ce1e76_0
  idna               pkgs/main/noarch::idna-3.3-pyhd3eb1b0_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_2
  openssl            pkgs/main/linux-64::openssl-1.1.1n-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.2.4-py39h06a4308_0
  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py39h27cfd23_0
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0
  pyopenssl          pkgs/main/noarch::pyopenssl-22.0.0-pyhd3eb1b0_0
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.12-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  requests           pkgs/main/noarch::requests-2.27.1-pyhd3eb1b0_0
  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.100-py39h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-61.2.0-py39h06a4308_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  sqlite             pkgs/main/linux-64::sqlite-3.38.2-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.11-h1ccaba5_0
  tqdm               pkgs/main/noarch::tqdm-4.63.0-pyhd3eb1b0_0
  tzdata             pkgs/main/noarch::tzdata-2022a-hda174b7_0
  urllib3            pkgs/main/noarch::urllib3-1.26.8-pyhd3eb1b0_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.12-h7f8727e_1


Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.

Creating conda environment...

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/GRAMES.POLYMTL.CA/p115628/miniforge3/envs/venv_sct

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-5.1          |            1_gnu          21 KB
    ca-certificates-2022.10.11 |       h06a4308_0         124 KB
    certifi-2022.9.24          |   py38h06a4308_0         154 KB
    ld_impl_linux-64-2.38      |       h1181459_1         654 KB
    libffi-3.4.2               |       h6a678d5_6         136 KB
    libgcc-ng-11.2.0           |       h1234567_1         5.3 MB
    libgomp-11.2.0             |       h1234567_1         474 KB
    libstdcxx-ng-11.2.0        |       h1234567_1         4.7 MB
    ncurses-6.3                |       h5eee18b_3         781 KB
    openssl-1.1.1s             |       h7f8727e_0         3.6 MB
    pip-22.3.1                 |   py38h06a4308_0         2.7 MB
    python-3.8.15              |       h7a1cb2a_2        20.1 MB
    readline-8.2               |       h5eee18b_0         357 KB
    setuptools-65.5.0          |   py38h06a4308_0         1.1 MB
    sqlite-3.40.0              |       h5082296_0         1.2 MB
    tk-8.6.12                  |       h1ccaba5_0         3.0 MB
    xz-5.2.8                   |       h5eee18b_0         429 KB
    zlib-1.2.13                |       h5eee18b_0         103 KB
    ------------------------------------------------------------
                                           Total:        44.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.10.11-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2022.9.24-py38h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.4.2-h6a678d5_6
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  ncurses            pkgs/main/linux-64::ncurses-6.3-h5eee18b_3
  openssl            pkgs/main/linux-64::openssl-1.1.1s-h7f8727e_0
  pip                pkgs/main/linux-64::pip-22.3.1-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.15-h7a1cb2a_2
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-65.5.0-py38h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.40.0-h5082296_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.8-h5eee18b_0
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0



Downloading and Extracting Packages
libgomp-11.2.0       | 474 KB    | ########## | 100% 
pip-22.3.1           | 2.7 MB    | ########## | 100% 
libstdcxx-ng-11.2.0  | 4.7 MB    | ########## | 100% 
ca-certificates-2022 | 124 KB    | ########## | 100% 
xz-5.2.8             | 429 KB    | ########## | 100% 
setuptools-65.5.0    | 1.1 MB    | ########## | 100% 
openssl-1.1.1s       | 3.6 MB    | ########## | 100% 
sqlite-3.40.0        | 1.2 MB    | ########## | 100% 
libgcc-ng-11.2.0     | 5.3 MB    | ########## | 100% 
_openmp_mutex-5.1    | 21 KB     | ########## | 100% 
python-3.8.15        | 20.1 MB   | ########## | 100% 
ld_impl_linux-64-2.3 | 654 KB    | ########## | 100% 
zlib-1.2.13          | 103 KB    | ########## | 100% 
readline-8.2         | 357 KB    | ########## | 100% 
tk-8.6.12            | 3.0 MB    | ########## | 100% 
certifi-2022.9.24    | 154 KB    | ########## | 100% 
ncurses-6.3          | 781 KB    | ########## | 100% 
libffi-3.4.2         | 136 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate venv_sct
#
# To deactivate an active environment, use
#
#     $ conda deactivate

./install_sct: ligne 605: /home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/python/envs/venv_sct/pyvenv.cfg: Aucun fichier ou dossier de ce type

Installation failed!

Please find the file "/home/GRAMES.POLYMTL.CA/p115628/spinalcordtoolbox/install_sct_log.txt",
then upload it as a .txt attachment in a new topic on SCT's forum:
--> http://forum.spinalcordmri.org/c/sct
```

</details>

### Discussion

This was discovered by @dpapp86. He was trying to use https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/ __which copied the conda installing code from SCT__, and additionally had a third install of conda just so he could [install fsleyes 1.5.0](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes#Install_from_conda-forge_.28recommended.29) (shimming-toolbox currently pins 1.4.x). So, three condas at a minimum, plus several sub-environments.

I'm not sure which of them was responsible for creating `.condarc`. Presumably at some point something ran `conda config --append envs_dirs ....` because at the time we found it he had:

```
% cat ~/.condarc
envs_dirs:
  - /Users/danielpapp/shimming-toolbox/python/envs/st_venv
  - /Users/danielpapp/shimming-toolbox/python/envs/st_venv/
  - /Users/danielpapp/shimming-toolbox/python/envs/
```

```
% cat ~/.conda/environments.txt 
/Users/danielpapp/miniconda/
/Users/danielpapp/miniconda/envs/dcm2bids
/Users/danielpapp/spinalcordtoolbox/python
/Users/danielpapp/shimming-toolbox/python/envs/st_venv/venv_sct
/Users/danielpapp/shimming-toolbox/python/envs/st_venv/
```

conda doesn't really live up to its promise as an isolation tool!

I recall (link somewhere?) that we discovered that creating or loading conda envs while already nested inside a conda env could be glitchy in incredibly difficult ways.

Here, I've discovered more ways this can fail: conda uses global ~/.condarc and ~/.conda/environments.txt, no matter which particular conda you're calling from.

But we are using it expecting that by installing to `~/spinalcordtoolbox/python/` then everything will be contained in that one folder.  I assume we got the idea from [the full FSL package](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation) which also does this, and now shimming-toolbox has copied the habit, adding to the complication.

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

Previously, when `-n` was used, there was a risk of the `venv_sct` conda environment being created in the global `$ENVS_DIRS` directory, rather than the expected `$SCT_DIR/python/envs/venv_sct`. This is because `-n` is supposed to be a *relative name* within the global conda envs dir. This global envs dir can be set by users using a `.condarc` file. But, SCT would prefer to ignore this global dir, and always create its env in `$SCT_DIR`.

So instead, we use `-p`, which specifies an absolute path, rather than a relative one. This means it is unaffected by the presence of `envs_dirs` in a `.condarc` file.

Further rationale is provided in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3982#issuecomment-1372585110.

## Linked issues

Fixes #3982.

### CODE REVIEW

**Review by kousu — APPROVED** [review]
Yep, looks good. Pre-approving.

I will give this a test run this evening under the reproduction condition you discovered to double-check your work. But it should be okay I think.

**Comment by mguaypaq** [comment]
@kousu, gentle ping: did you have a chance to test this fix?

**Comment by kousu** [comment]
Sorry, nope. I did not test.

**Comment by joshuacwnewton** [comment]
Thank you @mguaypaq! :hearts:

**Pull request merged**
