### PR TITLE
Update documentation to describe changes to `moco_params.tsv` for SCT v6.3

### PR DESCRIPTION
**Pull request by mguaypaq**
The columns were changed in #4396, but the tutorial changes should only be merged when SCT v6.3 gets released, since the website updates immediately.

### CODE REVIEW

**Comment by mguaypaq** [comment]
(I cancelled the CI test runs since there's no point running them right now.)

**Review by joshuacwnewton — APPROVED** [review]
The changes look good! Thank you for thinking ahead about the documentation changes. :)

**Comment by mguaypaq** [comment]
Since we're about to make the 6.3 release, I removed the "draft" status on this PR.

**Comment by joshuacwnewton** [comment]
Now that SCT v6.3 has been released, we can merge this PR. :)

**Pull request merged**
